// serverless/url-shortener/app/src/App.tsx
/**
 * URL Shortener App
 * Main application component with React OTP login
 */

import { useState, useEffect } from 'react';
import { apiClient } from './lib/api-client';
import UrlManager from './pages/UrlManager';
import { OtpLogin } from '@strixun/otp-login/dist/react';
import type { LoginSuccessData } from '@strixun/otp-login/dist/react';
import { getOtpEncryptionKey as getKey } from '../../../../shared-config/otp-encryption';
import './app.scss';

function getApiUrl(): string {
  if (typeof window === 'undefined') return '';
  return 'https://auth.idling.app';
}

function getOtpEncryptionKey(): string | undefined {
  return getKey();
}

async function fetchUserDisplayName(token: string): Promise<string | null> {
  try {
    const response = await fetch(`${getApiUrl()}/auth/me`, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
    });

    if (response.ok) {
      const data: any = await response.json();
      return data.displayName || null;
    }
  } catch (error) {
    console.error('[URL Shortener] Failed to fetch display name:', error);
  }
  return null;
}

export default function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [userDisplayName, setUserDisplayName] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function checkAuth() {
      const token = apiClient.getToken();
      
      if (token) {
        const displayName = await fetchUserDisplayName(token);
        if (displayName) {
          setIsAuthenticated(true);
          setUserDisplayName(displayName);
        }
      }
      
      setLoading(false);
    }
    
    checkAuth();
  }, []);

  async function handleLoginSuccess(data: LoginSuccessData): Promise<void> {
    const token = data.token;
    
    if (!token) {
      console.error('[URL Shortener] No token in login response');
      return;
    }
    
    apiClient.setToken(token);
    const displayName = await fetchUserDisplayName(token);
    
    setIsAuthenticated(true);
    setUserDisplayName(displayName);
  }

  function handleLoginError(error: string): void {
    console.error('[URL Shortener] Login error:', error);
  }

  function handleLogout(): void {
    apiClient.logout();
    setIsAuthenticated(false);
    setUserDisplayName(null);
  }

  if (loading) {
    return (
      <div className="app-container">
        <div className="loading">
          <div className="loading__spinner"></div>
          <p>Loading...</p>
        </div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="app-container">
        <div className="auth-container">
          <div className="auth-header">
            <h1>URL Shortener</h1>
            <p>Strixun Stream Suite - Create and manage short URLs with secure OTP authentication</p>
          </div>
          <div className="login-form">
            <OtpLogin
              apiUrl={getApiUrl()}
              onSuccess={handleLoginSuccess}
              onError={handleLoginError}
              otpEncryptionKey={getOtpEncryptionKey()}
              title="Sign In"
              subtitle="Enter your email to receive a verification code"
              endpoints={undefined}
              customHeaders={undefined}
              onClose={undefined}
            />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="app-container">
      <UrlManager userDisplayName={userDisplayName} onLogout={handleLogout} />
    </div>
  );
}

// serverless/url-shortener/app/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { apiClient } from '$lib/api-client';
  import type { LoginSuccessData } from '@shared-components/otp-login/core';
  import OtpLogin from '@shared-components/otp-login/svelte/OtpLogin.svelte';
  import UrlManager from './pages/UrlManager.svelte';

  let isAuthenticated = false;
  let userEmail: string | null = null;
  let loading = true;

  function getApiUrl(): string {
    if (typeof window === 'undefined') return '';
    // Use OTP auth service URL (same as main app)
    return 'https://auth.idling.app';
  }

  function getOtpEncryptionKey(): string | undefined {
    if (typeof window !== 'undefined' && (window as any).getOtpEncryptionKey) {
      return (window as any).getOtpEncryptionKey();
    }
    return undefined;
  }

  onMount(() => {
    // Check for stored token
    const token = apiClient.getToken();
    const storedEmail = typeof window !== 'undefined' 
      ? localStorage.getItem('urlShortenerEmail') 
      : null;
    
    if (token && storedEmail) {
      isAuthenticated = true;
      userEmail = storedEmail;
    }
    
    loading = false;
  });

  function handleLoginSuccess(data: LoginSuccessData): void {
    const token = data.access_token || data.token;
    const email = data.email;
    
    apiClient.setToken(token || null);
    if (typeof window !== 'undefined' && email) {
      localStorage.setItem('urlShortenerEmail', email);
    }
    
    isAuthenticated = true;
    userEmail = email;
  }

  function handleLoginError(error: string): void {
    console.error('Login error:', error);
  }

  function handleLogout(): void {
    apiClient.logout();
    isAuthenticated = false;
    userEmail = null;
  }
</script>

<div class="app-container">
  {#if loading}
    <div class="loading">
      <div class="loading__spinner"></div>
      <p>Loading...</p>
    </div>
  {:else if !isAuthenticated}
    <div class="auth-container">
      <div class="auth-header">
        <h1>🔗 URL Shortener</h1>
        <p>Strixun Stream Suite - Create and manage short URLs with secure OTP authentication</p>
      </div>
      <OtpLogin
        apiUrl={getApiUrl()}
        onSuccess={handleLoginSuccess}
        onError={handleLoginError}
        otpEncryptionKey={getOtpEncryptionKey()}
        title="Sign In"
        subtitle="Enter your email to receive a verification code"
      />
    </div>
  {:else}
    <UrlManager {userEmail} on:logout={handleLogout} />
  {/if}
</div>

<style>
  .app-container {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }

  .loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    color: var(--text-secondary);
  }

  .loading__spinner {
    display: inline-block;
    width: 40px;
    height: 40px;
    border: 3px solid var(--border);
    border-top-color: var(--accent);
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
    margin-bottom: var(--spacing-md);
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .auth-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    padding: var(--spacing-xl);
  }

  .auth-header {
    text-align: center;
    margin-bottom: var(--spacing-2xl);
  }

  .auth-header h1 {
    font-size: 2.5rem;
    font-weight: 600;
    margin-bottom: var(--spacing-md);
    color: var(--accent);
    text-shadow: 0 2px 4px rgba(237, 174, 73, 0.3);
  }

  .auth-header p {
    color: var(--text-secondary);
    font-size: 1.1rem;
  }
</style>
