// packages/chat/react/RoomCreator.tsx
/**
 * Room Creator Component
 * 
 * Form for creating a new chat room
 */

import { useState, useCallback } from 'react';

export interface RoomCreatorProps {
  /** Called when user creates a room */
  onCreateRoom: (customName?: string) => void;
  /** Called when user cancels */
  onCancel?: () => void;
  /** Loading state */
  loading?: boolean;
  /** Custom class name */
  className?: string;
}

export function RoomCreator({ 
  onCreateRoom, 
  onCancel,
  loading = false,
  className = ''
}: RoomCreatorProps) {
  const [roomName, setRoomName] = useState('');

  const handleSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    onCreateRoom(roomName.trim() || undefined);
  }, [roomName, onCreateRoom]);

  return (
    <div 
      className={`room-creator ${className}`}
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        padding: '16px',
      }}
    >
      <h3 
        style={{
          margin: '0 0 16px 0',
          fontSize: '1.125rem',
          fontWeight: 600,
          color: 'var(--text, #f9f9f9)',
        }}
      >
        Create New Room
      </h3>

      <form 
        onSubmit={handleSubmit}
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          flex: 1,
        }}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          <label 
            htmlFor="room-name"
            style={{
              fontSize: '0.875rem',
              fontWeight: 500,
              color: 'var(--text-secondary, #b0b0b0)',
            }}
          >
            Room Name (optional)
          </label>
          <input
            id="room-name"
            type="text"
            value={roomName}
            onChange={(e) => setRoomName(e.target.value)}
            placeholder="Enter a custom room name..."
            disabled={loading}
            style={{
              padding: '10px 12px',
              background: 'var(--bg, #1a1a1a)',
              border: '1px solid var(--border, #3a3a3a)',
              borderRadius: '4px',
              color: 'var(--text, #f9f9f9)',
              fontSize: '0.875rem',
              outline: 'none',
            }}
          />
          <p 
            style={{
              margin: 0,
              fontSize: '0.75rem',
              color: 'var(--text-muted, #808080)',
            }}
          >
            If left empty, your display name will be used as the room name.
          </p>
        </div>

        <div 
          style={{
            display: 'flex',
            gap: '12px',
            marginTop: 'auto',
          }}
        >
          {onCancel && (
            <button
              type="button"
              onClick={onCancel}
              disabled={loading}
              style={{
                flex: 1,
                padding: '12px',
                background: 'var(--bg-tertiary, #2d2d2d)',
                border: '1px solid var(--border, #3a3a3a)',
                borderRadius: '4px',
                color: 'var(--text, #f9f9f9)',
                fontSize: '0.875rem',
                cursor: loading ? 'not-allowed' : 'pointer',
              }}
            >
              Cancel
            </button>
          )}
          <button
            type="submit"
            disabled={loading}
            style={{
              flex: 1,
              padding: '12px',
              background: loading ? 'var(--bg-tertiary, #2d2d2d)' : 'var(--accent, #d4af37)',
              border: 'none',
              borderRadius: '4px',
              color: loading ? 'var(--text-muted, #808080)' : 'var(--bg, #1a1a1a)',
              fontSize: '0.875rem',
              fontWeight: 600,
              cursor: loading ? 'not-allowed' : 'pointer',
            }}
          >
            {loading ? 'Creating...' : 'Create Room'}
          </button>
        </div>
      </form>
    </div>
  );
}

// src/lib/components/chat/RoomCreator.svelte
<script lang="ts">
  /**
   * Room Creator Component
   * 
   * UI for creating or joining a room
   */

  import { createEventDispatcher } from 'svelte';
  import type { RoomManager } from '../../../services/chat/roomManager';

  const dispatch = createEventDispatcher();

  export let roomManager: RoomManager | null = null;

  let roomName: string = '';
  let roomId: string = '';
  let mode: 'create' | 'join' = 'create';
  let loading: boolean = false;

  function handleCreate() {
    if (mode === 'create') {
      dispatch('create', roomName || undefined);
    } else {
      dispatch('join', roomId);
    }
  }

  function handleCancel() {
    dispatch('cancel');
  }
</script>

<style lang="scss">
  @use '@styles/variables' as *;

  .room-creator {
    display: flex;
    flex-direction: column;
    padding: 24px;
    height: 100%;
  }

  .room-creator .room-creator__header {
    margin-bottom: 24px;
  }

  .room-creator .room-creator__title {
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--text);
    margin-bottom: 8px;
  }

  .room-creator .room-creator__tabs {
    display: flex;
    gap: 8px;
    margin-bottom: 24px;
  }

  .room-creator .room-creator__tab {
    padding: 8px 16px;
    background: transparent;
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--text-secondary);
    font-size: 0.9rem;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .room-creator .room-creator__tab--active {
    background: var(--primary);
    color: var(--text-on-primary);
    border-color: var(--primary);
  }

  .room-creator .room-creator__form {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  .room-creator .room-creator__field {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .room-creator .room-creator__label {
    font-size: 0.9rem;
    font-weight: 600;
    color: var(--text);
  }

  .room-creator .room-creator__input {
    padding: 10px 12px;
    background: var(--background);
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--text);
    font-size: 0.9rem;
    font-family: inherit;
  }

  .room-creator .room-creator__input:focus {
    outline: none;
    border-color: var(--primary);
  }

  .room-creator .room-creator__actions {
    display: flex;
    gap: 12px;
    margin-top: 8px;
  }

  .room-creator .room-creator__button {
    flex: 1;
    padding: 10px 16px;
    border: none;
    border-radius: 6px;
    font-size: 0.9rem;
    font-weight: 600;
    cursor: pointer;
    transition: background 0.2s ease;
  }

  .room-creator .room-creator__button--primary {
    background: var(--primary);
    color: var(--text-on-primary);
  }

  .room-creator .room-creator__button--primary:hover:not(:disabled) {
    background: var(--primary-hover);
  }

  .room-creator .room-creator__button--secondary {
    background: var(--background);
    color: var(--text);
    border: 1px solid var(--border);
  }

  .room-creator .room-creator__button--secondary:hover:not(:disabled) {
    background: var(--card-hover);
  }

  .room-creator .room-creator__button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>

<div class="room-creator">
  <div class="room-creator__header">
    <h2 class="room-creator__title">Chat Room</h2>
  </div>

  <div class="room-creator__tabs">
    <button
      class="room-creator__tab room-creator__tab--{mode === 'create' ? 'active' : ''}"
      on:click={() => (mode = 'create')}
      type="button"
    >
      Create Room
    </button>
    <button
      class="room-creator__tab room-creator__tab--{mode === 'join' ? 'active' : ''}"
      on:click={() => (mode = 'join')}
      type="button"
    >
      Join Room
    </button>
  </div>

  <div class="room-creator__form">
    {#if mode === 'create'}
      <div class="room-creator__field">
        <label for="room-name" class="room-creator__label">Room Name (Optional)</label>
        <input
          id="room-name"
          type="text"
          bind:value={roomName}
          placeholder="My Awesome Chat Room"
          class="room-creator__input"
        />
      </div>
    {:else}
      <div class="room-creator__field">
        <label for="room-id" class="room-creator__label">Room ID</label>
        <input
          id="room-id"
          type="text"
          bind:value={roomId}
          placeholder="Enter room ID to join"
          class="room-creator__input"
        />
      </div>
    {/if}

    <div class="room-creator__actions">
      <button
        on:click={handleCreate}
        disabled={loading || (mode === 'join' && !roomId.trim())}
        class="room-creator__button room-creator__button--primary"
        type="button"
      >
        {mode === 'create' ? 'Create' : 'Join'}
      </button>
      <button
        on:click={handleCancel}
        disabled={loading}
        class="room-creator__button room-creator__button--secondary"
        type="button"
      >
        Cancel
      </button>
    </div>
  </div>
</div>
