// shared-components/tooltip/Tooltip.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from 'svelte';
  
  export let content: string;
  export let position: 'top' | 'bottom' | 'left' | 'right' = 'top';
  export let delay: number = 200;
  export let maxWidth: string | null = null; // Optional override, null = use dynamic calculation
  export let maxHeight: string | null = null; // Optional max height, enables scrolling if content exceeds
  export let width: string | null = null; // Optional fixed width
  export let height: string | null = null; // Optional fixed height
  export let interactive: boolean = false; // If true, tooltip can be hovered and interacted with
  
  let showTooltip = false;
  let timeoutId: ReturnType<typeof setTimeout> | null = null;
  let tooltipWidth = '250px';
  let tooltipElement: HTMLDivElement;
  let wrapperElement: HTMLDivElement;
  let fixedStyle = '';
  let portalContainer: HTMLDivElement | null = null;
  let tooltipId = `tooltip-${Math.random().toString(36).substr(2, 9)}`;
  let isHoveringTooltip = false;
  let hideTimeoutId: ReturnType<typeof setTimeout> | null = null;
  
  // Portal action to render tooltip at body level
  function portal(node: HTMLElement, target: HTMLElement) {
    target.appendChild(node);
    return {
      update(newTarget: HTMLElement) {
        if (newTarget !== target) {
          newTarget.appendChild(node);
          target = newTarget;
        }
      },
      destroy() {
        if (node.parentNode) {
          node.parentNode.removeChild(node);
        }
      }
    };
  }
  
  // Calculate fixed position for tooltip
  function calculateFixedPosition(): string {
    if (!wrapperElement || !tooltipElement) return '';
    
    const rect = wrapperElement.getBoundingClientRect();
    const tooltipRect = tooltipElement.getBoundingClientRect();
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;
    
    let top = 0;
    let left = 0;
    
    switch (position) {
      case 'top':
        top = rect.top - tooltipRect.height - 8;
        left = rect.left + (rect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'bottom':
        top = rect.bottom + 8;
        left = rect.left + (rect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'left':
        top = rect.top + (rect.height / 2) - (tooltipRect.height / 2);
        left = rect.left - tooltipRect.width - 8;
        break;
      case 'right':
        top = rect.top + (rect.height / 2) - (tooltipRect.height / 2);
        left = rect.right + 8;
        break;
    }
    
    // Keep tooltip within viewport
    if (left < 8) left = 8;
    if (left + tooltipRect.width > viewportWidth - 8) {
      left = viewportWidth - tooltipRect.width - 8;
    }
    if (top < 8) top = 8;
    if (top + tooltipRect.height > viewportHeight - 8) {
      top = viewportHeight - tooltipRect.height - 8;
    }
    
    return `top: ${top}px; left: ${left}px;`;
  }
  
  // Calculate dynamic width based on viewport, max 45%
  function calculateTooltipWidth(): string {
    // Use override if provided
    if (maxWidth !== null) {
      return maxWidth;
    }
    
    if (typeof window === 'undefined') return '250px';
    const viewportWidth = window.innerWidth;
    const calculatedMaxWidth = Math.floor(viewportWidth * 0.45);
    const minWidth = 250;
    return `${Math.max(minWidth, calculatedMaxWidth)}px`;
  }
  
  function updateTooltipWidth() {
    tooltipWidth = calculateTooltipWidth();
  }
  
  // Build dimension styles
  function buildDimensionStyles(): string {
    const styles: string[] = [];
    
    if (width !== null) {
      styles.push(`width: ${width}`);
    }
    if (height !== null) {
      styles.push(`height: ${height}`);
    }
    if (maxWidth !== null) {
      styles.push(`max-width: ${maxWidth}`);
    } else {
      // Use calculated width if maxWidth not provided
      styles.push(`max-width: ${tooltipWidth}`);
    }
    if (maxHeight !== null) {
      styles.push(`max-height: ${maxHeight}`);
    }
    
    return styles.join('; ');
  }
  
  // Update width when maxWidth prop changes
  $: if (maxWidth !== null || typeof window !== 'undefined') {
    tooltipWidth = calculateTooltipWidth();
  }
  
  // Reactive dimension styles
  $: dimensionStyles = buildDimensionStyles();
  
  async function handleMouseEnter() {
    if (timeoutId) clearTimeout(timeoutId);
    timeoutId = setTimeout(async () => {
      showTooltip = true;
      updateTooltipWidth();
      
      // Wait for tooltip to render, then calculate position
      await tick();
      if (tooltipElement && wrapperElement) {
        await tick(); // Wait for tooltip to render
        fixedStyle = calculateFixedPosition();
      }
    }, delay);
  }
  
  function handleMouseLeave() {
    if (timeoutId) clearTimeout(timeoutId);
    timeoutId = null;
    
    if (!interactive) {
      // Non-interactive: hide immediately
      showTooltip = false;
      fixedStyle = '';
      return;
    }
    
    // Interactive: delay hiding to allow moving to tooltip
    if (hideTimeoutId) clearTimeout(hideTimeoutId);
    hideTimeoutId = setTimeout(() => {
      if (!isHoveringTooltip) {
        showTooltip = false;
        fixedStyle = '';
      }
      hideTimeoutId = null;
    }, 100); // Small delay to bridge gap between trigger and tooltip
  }
  
  function handleTooltipMouseEnter() {
    if (interactive) {
      // Cancel any pending hide
      if (hideTimeoutId) {
        clearTimeout(hideTimeoutId);
        hideTimeoutId = null;
      }
      isHoveringTooltip = true;
    }
  }
  
  function handleTooltipMouseLeave() {
    if (interactive) {
      isHoveringTooltip = false;
      // Small delay to allow moving mouse from tooltip back to trigger
      if (hideTimeoutId) clearTimeout(hideTimeoutId);
      hideTimeoutId = setTimeout(() => {
        if (!isHoveringTooltip) {
          showTooltip = false;
          fixedStyle = '';
        }
        hideTimeoutId = null;
      }, 100);
    }
  }
  
  function handleResize() {
    // Only update if using dynamic width (maxWidth is null)
    if (maxWidth === null) {
      updateTooltipWidth();
    }
    if (showTooltip && tooltipElement && wrapperElement) {
      fixedStyle = calculateFixedPosition();
    }
  }
  
  onMount(() => {
    tooltipWidth = calculateTooltipWidth();
    
    // Create portal container at body level for tooltip
    portalContainer = document.createElement('div');
    portalContainer.id = `tooltip-portal-${tooltipId}`;
    portalContainer.style.position = 'fixed';
    portalContainer.style.top = '0';
    portalContainer.style.left = '0';
    portalContainer.style.width = '0';
    portalContainer.style.height = '0';
    portalContainer.style.pointerEvents = 'none';
    portalContainer.style.zIndex = '1000001'; // Above modal (1000000)
    document.body.appendChild(portalContainer);
    
    window.addEventListener('resize', handleResize);
    window.addEventListener('scroll', handleResize, true);
  });
  
  onDestroy(() => {
    if (timeoutId) clearTimeout(timeoutId);
    if (hideTimeoutId) clearTimeout(hideTimeoutId);
    if (typeof window !== 'undefined') {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('scroll', handleResize, true);
    }
    // Clean up portal container
    if (portalContainer && portalContainer.parentNode) {
      portalContainer.parentNode.removeChild(portalContainer);
    }
  });
  
  // Update position when tooltip is shown
  $: if (showTooltip && tooltipElement && wrapperElement) {
    tick().then(() => {
      fixedStyle = calculateFixedPosition();
    });
  }
</script>

<div 
  class="tooltip-wrapper"
  bind:this={wrapperElement}
  onmouseenter={handleMouseEnter}
  onmouseleave={handleMouseLeave}
>
  <slot />
</div>

{#if showTooltip && portalContainer}
  <div 
    class="tooltip tooltip--{position}" 
    class:tooltip--interactive={interactive}
    class:tooltip--scrollable={maxHeight !== null || height !== null}
    role="tooltip" 
    style="{dimensionStyles}; {fixedStyle}"
    bind:this={tooltipElement}
    use:portal={portalContainer}
    onmouseenter={handleTooltipMouseEnter}
    onmouseleave={handleTooltipMouseLeave}
  >
    <div class="tooltip-content">
      {@html content}
    </div>
    <div class="tooltip-arrow"></div>
  </div>
{/if}

<style>
  .tooltip-wrapper {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }
  
  .tooltip {
    position: fixed;
    z-index: 1000001; /* Above modal (1000000) */
    background: var(--tooltip-bg, #2a2a2a);
    color: var(--tooltip-text, #ffffff);
    padding: 16px 20px;
    border-radius: 8px;
    font-size: 0.875rem;
    line-height: 1.6;
    min-width: 280px;
    max-width: 500px;
    border: 1px solid rgba(255, 255, 255, 0.2);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.1);
    pointer-events: none;
    white-space: normal;
    word-wrap: break-word;
    transform: none;
    margin: 0;
    display: flex;
    flex-direction: column;
    box-sizing: border-box;
  }
  
  .tooltip--interactive {
    pointer-events: auto;
  }
  
  .tooltip--scrollable {
    overflow: hidden;
  }
  
  .tooltip--scrollable .tooltip-content {
    overflow-y: auto;
    overflow-x: hidden;
    flex: 1;
    min-height: 0;
    /* Custom scrollbar styling */
    scrollbar-width: thin;
    scrollbar-color: rgba(255, 255, 255, 0.3) transparent;
    /* Add padding to account for scrollbar */
    padding-right: 4px;
    margin-right: -4px;
  }
  
  .tooltip--scrollable .tooltip-content::-webkit-scrollbar {
    width: 8px;
  }
  
  .tooltip--scrollable .tooltip-content::-webkit-scrollbar-track {
    background: transparent;
    border-radius: 4px;
    margin: 4px 0;
  }
  
  .tooltip--scrollable .tooltip-content::-webkit-scrollbar-thumb {
    background: rgba(255, 255, 255, 0.3);
    border-radius: 4px;
    border: 2px solid transparent;
    background-clip: padding-box;
  }
  
  .tooltip--scrollable .tooltip-content::-webkit-scrollbar-thumb:hover {
    background: rgba(255, 255, 255, 0.5);
    background-clip: padding-box;
  }
  
  .tooltip-content {
    position: relative;
    z-index: 1;
  }
  
  .tooltip-arrow {
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
  }
  
  .tooltip--top .tooltip-arrow {
    top: 100%;
    left: 50%;
    transform: translateX(-50%);
    border-width: 6px 6px 0 6px;
    border-color: var(--tooltip-bg, #2a2a2a) transparent transparent transparent;
  }
  
  .tooltip--bottom .tooltip-arrow {
    bottom: 100%;
    left: 50%;
    transform: translateX(-50%);
    border-width: 0 6px 6px 6px;
    border-color: transparent transparent var(--tooltip-bg, #2a2a2a) transparent;
  }
  
  .tooltip--left .tooltip-arrow {
    left: 100%;
    top: 50%;
    transform: translateY(-50%);
    border-width: 6px 0 6px 6px;
    border-color: transparent transparent transparent var(--tooltip-bg, #2a2a2a);
  }
  
  .tooltip--right .tooltip-arrow {
    right: 100%;
    top: 50%;
    transform: translateY(-50%);
    border-width: 6px 6px 6px 0;
    border-color: transparent var(--tooltip-bg, #2a2a2a) transparent transparent;
  }
</style>

// mods-hub/src/components/common/Tooltip.tsx
/**
 * Tooltip Component
 * 
 * Portal-enabled tooltip component that prevents content shift and ensures
 * tooltip stays within viewport bounds. Matches main app's smart tooltip behavior.
 * 
 * @example
 * <Tooltip text="Click to copy">
 *   <button>Copy</button>
 * </Tooltip>
 */

import { useState, useRef, useEffect, useCallback, ReactNode } from 'react';
import { createPortal } from 'react-dom';
import styled, { css } from 'styled-components';
import { colors, spacing } from '../../theme';

type TooltipPosition = 'top' | 'bottom' | 'left' | 'right' | 'auto';

interface TooltipProps {
  text: string;
  position?: TooltipPosition;
  delay?: number;
  disabled?: boolean;
  maxWidth?: string | null;
  children: ReactNode;
}

const TooltipWrapper = styled.div`
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
`;

const TooltipElement = styled.div<{ 
  $position: 'top' | 'bottom' | 'left' | 'right';
  $maxWidth?: string;
}>`
  position: fixed;
  z-index: 100002; /* Highest - above modals and toasts */
  padding: 6px 10px;
  background: var(--card, ${colors.bgSecondary});
  border: 1px solid var(--border, ${colors.border});
  color: var(--text, ${colors.text});
  font-size: 0.85em;
  line-height: 1.4;
  pointer-events: none;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  border-radius: 4px;
  white-space: normal;
  word-wrap: break-word;
  overflow-wrap: break-word;
  text-align: center;
  display: inline-block;
  max-width: ${props => props.$maxWidth || '300px'};
  min-width: 200px;
  
  /* Arrow styles */
  &::after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
  }
  
  &::before {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
    z-index: -1;
  }
  
  /* Top position - arrow points down */
  ${props => props.$position === 'top' && css`
    &::after {
      top: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 5px 5px 0 5px;
      border-color: var(--card, ${colors.bgSecondary}) transparent transparent transparent;
    }
    
    &::before {
      top: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 6px 6px 0 6px;
      border-color: var(--border, ${colors.border}) transparent transparent transparent;
      margin-top: -1px;
    }
  `}
  
  /* Bottom position - arrow points up */
  ${props => props.$position === 'bottom' && css`
    &::after {
      bottom: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 0 5px 5px 5px;
      border-color: transparent transparent var(--card, ${colors.bgSecondary}) transparent;
    }
    
    &::before {
      bottom: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 0 6px 6px 6px;
      border-color: transparent transparent var(--border, ${colors.border}) transparent;
      margin-bottom: -1px;
    }
  `}
  
  /* Left position - arrow points right */
  ${props => props.$position === 'left' && css`
    &::after {
      left: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 5px 0 5px 5px;
      border-color: transparent transparent transparent var(--card, ${colors.bgSecondary});
    }
    
    &::before {
      left: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 6px 0 6px 6px;
      border-color: transparent transparent transparent var(--border, ${colors.border});
      margin-left: -1px;
    }
  `}
  
  /* Right position - arrow points left */
  ${props => props.$position === 'right' && css`
    &::after {
      right: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 5px 5px 5px 0;
      border-color: transparent var(--card, ${colors.bgSecondary}) transparent transparent;
    }
    
    &::before {
      right: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 6px 6px 6px 0;
      border-color: transparent var(--border, ${colors.border}) transparent transparent;
      margin-right: -1px;
    }
  `}
`;

export function Tooltip({ 
  text, 
  position = 'auto', 
  delay = 0, 
  disabled = false,
  maxWidth = null,
  children 
}: TooltipProps) {
  const [show, setShow] = useState(false);
  const [actualPosition, setActualPosition] = useState<'top' | 'bottom' | 'left' | 'right'>('top');
  const [tooltipStyle, setTooltipStyle] = useState<React.CSSProperties>({});
  const wrapperRef = useRef<HTMLDivElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);
  const portalContainerRef = useRef<HTMLDivElement | null>(null);
  const hoverTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const listenersActiveRef = useRef(false);

  // Calculate max width based on viewport
  const calculateMaxWidth = useCallback((): string => {
    if (maxWidth !== null) {
      return maxWidth;
    }
    if (typeof window === 'undefined') return '300px';
    const viewportWidth = window.innerWidth;
    const calculated = Math.max(200, Math.min(500, Math.floor(viewportWidth * 0.4)));
    return `${calculated}px`;
  }, [maxWidth]);

  // Calculate best position based on available space
  const calculatePosition = useCallback((): 'top' | 'bottom' | 'left' | 'right' => {
    if (position !== 'auto') {
      return position;
    }

    if (!wrapperRef.current || !tooltipRef.current) {
      return 'top';
    }

    const triggerRect = wrapperRef.current.getBoundingClientRect();
    const tooltipRect = tooltipRef.current.getBoundingClientRect();
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;

    // Check available space in each direction
    const spaceTop = triggerRect.top;
    const spaceBottom = viewportHeight - triggerRect.bottom;
    const spaceLeft = triggerRect.left;
    const spaceRight = viewportWidth - triggerRect.right;

    // Determine best position
    if (spaceBottom >= tooltipRect.height + 10) {
      return 'bottom';
    } else if (spaceTop >= tooltipRect.height + 10) {
      return 'top';
    } else if (spaceRight >= tooltipRect.width + 10) {
      return 'right';
    } else if (spaceLeft >= tooltipRect.width + 10) {
      return 'left';
    } else {
      return 'bottom'; // Default fallback
    }
  }, [position]);

  // Update tooltip position using fixed positioning
  const updateTooltipPosition = useCallback(() => {
    if (!wrapperRef.current || !tooltipRef.current) return;

    const triggerRect = wrapperRef.current.getBoundingClientRect();
    const tooltipRect = tooltipRef.current.getBoundingClientRect();
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;

    let top = 0;
    let left = 0;
    const padding = 8;

    switch (actualPosition) {
      case 'top':
        top = triggerRect.top - tooltipRect.height - padding;
        left = triggerRect.left + (triggerRect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'bottom':
        top = triggerRect.bottom + padding;
        left = triggerRect.left + (triggerRect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'left':
        top = triggerRect.top + (triggerRect.height / 2) - (tooltipRect.height / 2);
        left = triggerRect.left - tooltipRect.width - padding;
        break;
      case 'right':
        top = triggerRect.top + (triggerRect.height / 2) - (tooltipRect.height / 2);
        left = triggerRect.right + padding;
        break;
    }

    // Keep tooltip within viewport bounds
    if (left < padding) left = padding;
    if (left + tooltipRect.width > viewportWidth - padding) {
      left = viewportWidth - tooltipRect.width - padding;
    }
    if (top < padding) top = padding;
    if (top + tooltipRect.height > viewportHeight - padding) {
      top = viewportHeight - tooltipRect.height - padding;
    }

    setTooltipStyle({
      top: `${top}px`,
      left: `${left}px`,
      maxWidth: calculateMaxWidth(),
    });
  }, [actualPosition, calculateMaxWidth]);

  // Handle resize and scroll events
  const handleResize = useCallback(() => {
    if (show && tooltipRef.current) {
      const newPosition = calculatePosition();
      setActualPosition(newPosition);
      updateTooltipPosition();
    }
  }, [show, calculatePosition, updateTooltipPosition]);

  // Show tooltip
  const handleMouseEnter = useCallback(() => {
    if (disabled || !text) return;

    if (delay > 0) {
      hoverTimeoutRef.current = setTimeout(() => {
        setShow(true);
        hoverTimeoutRef.current = null;
      }, delay);
    } else {
      setShow(true);
    }
  }, [disabled, text, delay]);

  // Hide tooltip
  const handleMouseLeave = useCallback(() => {
    if (hoverTimeoutRef.current) {
      clearTimeout(hoverTimeoutRef.current);
      hoverTimeoutRef.current = null;
    }
    setShow(false);
  }, []);

  // Create portal container on mount
  useEffect(() => {
    if (typeof document === 'undefined') return;

    const portalContainer = document.createElement('div');
    portalContainer.id = `tooltip-portal-${Math.random().toString(36).substr(2, 9)}`;
    portalContainer.style.position = 'fixed';
    portalContainer.style.top = '0';
    portalContainer.style.left = '0';
    portalContainer.style.width = '0';
    portalContainer.style.height = '0';
    portalContainer.style.pointerEvents = 'none';
    portalContainer.style.zIndex = '100002';
    document.body.appendChild(portalContainer);
    portalContainerRef.current = portalContainer;

    return () => {
      if (portalContainerRef.current && portalContainerRef.current.parentNode) {
        portalContainerRef.current.parentNode.removeChild(portalContainerRef.current);
      }
    };
  }, []);

  // Update position when tooltip becomes visible
  useEffect(() => {
    if (show && tooltipRef.current && wrapperRef.current) {
      // Wait for tooltip to render, then calculate position
      requestAnimationFrame(() => {
        if (!tooltipRef.current || !wrapperRef.current) return;
        
        const newPosition = calculatePosition();
        setActualPosition(newPosition);
        updateTooltipPosition();

        // Add event listeners if not already active
        if (!listenersActiveRef.current) {
          window.addEventListener('resize', handleResize);
          window.addEventListener('scroll', handleResize, true);
          listenersActiveRef.current = true;
        }
      });
    }

    return () => {
      if (!show && listenersActiveRef.current) {
        window.removeEventListener('resize', handleResize);
        window.removeEventListener('scroll', handleResize, true);
        listenersActiveRef.current = false;
      }
    };
  }, [show, calculatePosition, updateTooltipPosition, handleResize]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (hoverTimeoutRef.current) {
        clearTimeout(hoverTimeoutRef.current);
      }
      if (listenersActiveRef.current) {
        window.removeEventListener('resize', handleResize);
        window.removeEventListener('scroll', handleResize, true);
      }
    };
  }, [handleResize]);

  if (!text || disabled) {
    return <>{children}</>;
  }

  return (
    <>
      <TooltipWrapper
        ref={wrapperRef}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        {children}
      </TooltipWrapper>
      {show && portalContainerRef.current && createPortal(
        <TooltipElement
          ref={tooltipRef}
          $position={actualPosition}
          $maxWidth={calculateMaxWidth()}
          style={tooltipStyle}
          role="tooltip"
        >
          {text}
        </TooltipElement>,
        portalContainerRef.current
      )}
    </>
  );
}
