// shared-components/react/CodeBlock.tsx
import React, { useEffect, useRef, useState } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-jsx';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-tsx';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-scss';
import 'prismjs/components/prism-http';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-python';
import 'prismjs/components/prism-markup';
import 'prismjs/themes/prism-tomorrow.css';
import './CodeBlock.css';

interface CodeBlockProps {
  code: string;
  language?: string;
}

export function CodeBlock({ code, language = 'javascript' }: CodeBlockProps) {
  const codeRef = useRef<HTMLElement>(null);
  const [copied, setCopied] = useState(false);

  // Map languages to Prism-supported languages
  const prismLanguage = (() => {
    if (language === 'svelte') return 'markup';
    if (language === 'html') return 'markup';
    if (language === 'ts') return 'typescript';
    if (language === 'js') return 'javascript';
    return language;
  })();

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Highlight on mount and when code/language changes
  useEffect(() => {
    if (codeRef.current) {
      Prism.highlightElement(codeRef.current);
    }
  }, [code, prismLanguage]);

  return (
    <div className="code-block-wrapper">
      <button
        className={`copy-button ${copied ? 'copied' : ''}`}
        onClick={copyToClipboard}
        aria-label="Copy code to clipboard"
        title={copied ? 'Copied!' : 'Copy code'}
      >
        {copied ? (
          <>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M13.5 4L6 11.5L2.5 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            <span>Copied!</span>
          </>
        ) : (
          <>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <rect x="5" y="5" width="9" height="9" rx="1" stroke="currentColor" strokeWidth="1.5" fill="none"/>
              <path d="M3 3V11C3 11.5523 3.44772 12 4 12H11" stroke="currentColor" strokeWidth="1.5" fill="none"/>
            </svg>
            <span>Copy</span>
          </>
        )}
      </button>
      <pre>
        <code ref={codeRef} className={`language-${prismLanguage}`}>
          {code}
        </code>
      </pre>
    </div>
  );
}

// serverless/otp-auth-service/src/lib/CodeBlock.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Prism from 'prismjs';
  import 'prismjs/components/prism-javascript';
  import 'prismjs/components/prism-jsx';
  import 'prismjs/components/prism-typescript';
  import 'prismjs/components/prism-tsx';
  import 'prismjs/components/prism-json';
  import 'prismjs/components/prism-css';
  import 'prismjs/components/prism-scss';
  import 'prismjs/components/prism-http';
  import 'prismjs/components/prism-bash';
  import 'prismjs/components/prism-python';
  import 'prismjs/components/prism-markup';
  import 'prismjs/themes/prism-tomorrow.css';

  export let code: string;
  export let language: string = 'javascript';

  let codeElement: HTMLElement;
  let copied = false;

  // Map languages to Prism-supported languages
  $: prismLanguage = (() => {
    if (language === 'svelte') return 'markup';
    if (language === 'html') return 'markup';
    if (language === 'ts') return 'typescript';
    if (language === 'js') return 'javascript';
    return language;
  })();

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(code);
      copied = true;
      setTimeout(() => {
        copied = false;
      }, 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  }

  // Re-highlight when code or language changes
  $: if (codeElement && code && prismLanguage) {
    Prism.highlightElement(codeElement);
  }

  onMount(() => {
    if (codeElement) {
      Prism.highlightElement(codeElement);
    }
  });
</script>

<div class="code-block-wrapper">
  <button
    class="copy-button"
    class:copied={copied}
    on:click={copyToClipboard}
    aria-label="Copy code to clipboard"
    title={copied ? 'Copied!' : 'Copy code'}
  >
    {#if copied}
      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M13.5 4L6 11.5L2.5 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
      <span>Copied!</span>
    {:else}
      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="5" y="5" width="9" height="9" rx="1" stroke="currentColor" stroke-width="1.5" fill="none"/>
        <path d="M3 3V11C3 11.5523 3.44772 12 4 12H11" stroke="currentColor" stroke-width="1.5" fill="none"/>
      </svg>
      <span>Copy</span>
    {/if}
  </button>
  <pre><code class="language-{prismLanguage}" bind:this={codeElement}>{code}</code></pre>
</div>

<style>
  .code-block-wrapper {
    position: relative;
    margin: var(--spacing-md) 0;
  }

  .copy-button {
    position: absolute;
    top: var(--spacing-sm);
    right: var(--spacing-sm);
    display: flex;
    align-items: center;
    gap: var(--spacing-xs);
    padding: var(--spacing-xs) var(--spacing-sm);
    background: var(--bg-dark);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    color: var(--text-secondary);
    font-size: 0.75rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    z-index: 10;
    font-family: inherit;
  }

  .copy-button:hover {
    background: var(--bg);
    color: var(--text);
    border-color: var(--border-light);
  }

  .copy-button:active {
    transform: scale(0.95);
  }

  .copy-button.copied {
    background: var(--accent);
    border-color: var(--accent);
    color: var(--bg-dark);
  }

  .copy-button svg {
    flex-shrink: 0;
    width: 16px;
    height: 16px;
  }

  .copy-button span {
    white-space: nowrap;
  }

  pre {
    background: var(--bg-dark);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    padding: var(--spacing-lg);
    overflow-x: auto;
    overflow-y: auto;
    max-height: 400px;
    margin: 0;
  }

  code {
    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', monospace;
    font-size: 0.875rem;
    line-height: 1.6;
  }

  @media (max-width: 768px) {
    .copy-button span {
      display: none;
    }

    .copy-button {
      padding: var(--spacing-xs);
    }
  }
</style>
