// src/lib/components/chat/RoomList.svelte
<script lang="ts">
  /**
   * Room List Component
   * 
   * Displays available rooms to join
   */

  import { createEventDispatcher, onMount } from 'svelte';
  import type { RoomManager } from '../../../services/chat/roomManager';
  import type { RoomMetadata } from '../../../types/chat';

  const dispatch = createEventDispatcher();

  export let roomManager: RoomManager | null = null;
  export let showRoomCreator: boolean = true;

  let rooms: RoomMetadata[] = [];
  let loading: boolean = true;
  let error: string | null = null;

  onMount(async () => {
    await loadRooms();
  });

  async function loadRooms() {
    if (!roomManager) {
      loading = false;
      return;
    }

    try {
      loading = true;
      error = null;
      rooms = await roomManager.getActiveRooms();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to load rooms';
    } finally {
      loading = false;
    }
  }

  function handleJoin(roomId: string) {
    dispatch('join', roomId);
  }

  function handleCreate() {
    dispatch('create');
  }
</script>

<style lang="scss">
  @use '@styles/variables' as *;

  .room-list {
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 16px;
  }

  .room-list .room-list__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 16px;
  }

  .room-list .room-list__title {
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--text);
  }

  .room-list .room-list__create-button {
    padding: 8px 16px;
    background: var(--primary);
    color: var(--text-on-primary);
    border: none;
    border-radius: 6px;
    font-size: 0.9rem;
    font-weight: 600;
    cursor: pointer;
    transition: background 0.2s ease;
  }

  .room-list .room-list__create-button:hover {
    background: var(--primary-hover);
  }

  .room-list .room-list__content {
    flex: 1;
    overflow-y: auto;
  }

  .room-list .room-list__room {
    padding: 12px;
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 6px;
    margin-bottom: 8px;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .room-list .room-list__room:hover {
    background: var(--card-hover);
    border-color: var(--primary);
  }

  .room-list .room-list__room-name {
    font-size: 1rem;
    font-weight: 600;
    color: var(--text);
    margin-bottom: 4px;
  }

  .room-list .room-list__room-info {
    display: flex;
    align-items: center;
    gap: 12px;
    font-size: 0.85rem;
    color: var(--text-secondary);
  }

  .room-list .room-list__empty {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--text-secondary);
    font-size: 0.9rem;
  }

  .room-list .room-list__loading {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--text-secondary);
    font-size: 0.9rem;
  }

  .room-list .room-list__error {
    padding: 12px;
    background: var(--error-bg);
    color: var(--error);
    border-radius: 6px;
    font-size: 0.85rem;
    margin-bottom: 16px;
  }
</style>

<div class="room-list">
  <div class="room-list__header">
    <h2 class="room-list__title">Available Rooms</h2>
    {#if showRoomCreator}
      <button on:click={handleCreate} class="room-list__create-button" type="button">
        Create Room
      </button>
    {/if}
  </div>

  {#if error}
    <div class="room-list__error">{error}</div>
  {/if}

  <div class="room-list__content">
    {#if loading}
      <div class="room-list__loading">Loading rooms...</div>
    {:else if rooms.length === 0}
      <div class="room-list__empty">
        No rooms available. {#if showRoomCreator}Create one to get started!{/if}
      </div>
    {:else}
      {#each rooms as room (room.roomId)}
        <div class="room-list__room" on:click={() => handleJoin(room.roomId)} role="button" tabindex="0">
          <div class="room-list__room-name">
            {room.customName || room.broadcasterName}
          </div>
          <div class="room-list__room-info">
            <span>[USER] {room.participantCount}</span>
            <span>•</span>
            <span>by {room.broadcasterName}</span>
          </div>
        </div>
      {/each}
    {/if}
  </div>
</div>

// packages/chat/react/RoomList.tsx
/**
 * Room List Component
 * 
 * Displays list of available chat rooms
 */

import { useEffect, useState, useCallback } from 'react';
import type { RoomMetadata } from '../core/types.js';

export interface RoomListProps {
  /** Function to fetch active rooms */
  fetchRooms: () => Promise<RoomMetadata[]>;
  /** Called when user wants to join a room */
  onJoinRoom: (roomId: string) => void;
  /** Called when user wants to create a room */
  onCreateRoom?: () => void;
  /** Show create room button */
  showCreateButton?: boolean;
  /** Custom class name */
  className?: string;
}

export function RoomList({ 
  fetchRooms,
  onJoinRoom, 
  onCreateRoom,
  showCreateButton = true,
  className = ''
}: RoomListProps) {
  const [rooms, setRooms] = useState<RoomMetadata[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadRooms = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const activeRooms = await fetchRooms();
      setRooms(activeRooms);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load rooms');
    } finally {
      setLoading(false);
    }
  }, [fetchRooms]);

  useEffect(() => {
    loadRooms();
    
    // Refresh rooms every 30 seconds
    const interval = setInterval(loadRooms, 30000);
    return () => clearInterval(interval);
  }, [loadRooms]);

  return (
    <div 
      className={`room-list ${className}`}
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        padding: '16px',
      }}
    >
      <div 
        className="room-list__header"
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: '16px',
        }}
      >
        <h3 
          style={{
            margin: 0,
            fontSize: '1.125rem',
            fontWeight: 600,
            color: 'var(--text, #f9f9f9)',
          }}
        >
          Active Rooms
        </h3>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            onClick={loadRooms}
            disabled={loading}
            style={{
              padding: '6px 12px',
              background: 'var(--bg-tertiary, #2d2d2d)',
              border: '1px solid var(--border, #3a3a3a)',
              borderRadius: '4px',
              color: 'var(--text, #f9f9f9)',
              fontSize: '0.75rem',
              cursor: loading ? 'not-allowed' : 'pointer',
            }}
          >
            {loading ? 'Loading...' : 'Refresh'}
          </button>
          {showCreateButton && onCreateRoom && (
            <button
              onClick={onCreateRoom}
              style={{
                padding: '6px 12px',
                background: 'var(--accent, #d4af37)',
                border: 'none',
                borderRadius: '4px',
                color: 'var(--bg, #1a1a1a)',
                fontSize: '0.75rem',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              Create Room
            </button>
          )}
        </div>
      </div>

      {error && (
        <div 
          style={{
            padding: '12px',
            background: 'rgba(244, 67, 54, 0.1)',
            color: 'var(--danger, #f44336)',
            borderRadius: '4px',
            marginBottom: '16px',
            fontSize: '0.875rem',
          }}
        >
          {error}
        </div>
      )}

      <div 
        className="room-list__rooms"
        style={{
          flex: 1,
          overflowY: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
        }}
      >
        {loading && rooms.length === 0 ? (
          <div 
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              height: '100%',
              color: 'var(--text-muted, #808080)',
            }}
          >
            Loading rooms...
          </div>
        ) : rooms.length === 0 ? (
          <div 
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              height: '100%',
              gap: '12px',
              color: 'var(--text-muted, #808080)',
            }}
          >
            <span>No active rooms</span>
            {showCreateButton && onCreateRoom && (
              <button
                onClick={onCreateRoom}
                style={{
                  padding: '8px 16px',
                  background: 'var(--accent, #d4af37)',
                  border: 'none',
                  borderRadius: '4px',
                  color: 'var(--bg, #1a1a1a)',
                  fontSize: '0.875rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                }}
              >
                Create First Room
              </button>
            )}
          </div>
        ) : (
          rooms.map((room) => (
            <div
              key={room.roomId}
              className="room-list__room"
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '12px 16px',
                background: 'var(--bg-secondary, #252525)',
                border: '1px solid var(--border, #3a3a3a)',
                borderRadius: '4px',
              }}
            >
              <div>
                <div 
                  style={{
                    fontWeight: 600,
                    color: 'var(--text, #f9f9f9)',
                    marginBottom: '4px',
                  }}
                >
                  {room.customName || room.broadcasterName}
                </div>
                <div 
                  style={{
                    fontSize: '0.75rem',
                    color: 'var(--text-muted, #808080)',
                  }}
                >
                  {room.participantCount} participant{room.participantCount !== 1 ? 's' : ''}
                </div>
              </div>
              <button
                onClick={() => onJoinRoom(room.roomId)}
                style={{
                  padding: '6px 16px',
                  background: 'var(--accent, #d4af37)',
                  border: 'none',
                  borderRadius: '4px',
                  color: 'var(--bg, #1a1a1a)',
                  fontSize: '0.75rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                }}
              >
                Join
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
