// shared-components/svelte/ObfuscatedText.svelte
<script lang="ts">
  /**
   * ObfuscatedText Component
   * 
   * A reusable component for displaying obfuscated/scrambled text using various character sets.
   * Perfect for hiding undecided values, redacting sensitive information, or creating mysterious text effects.
   * 
   * @example
   * ```svelte
   * <ObfuscatedText text="$99.99" />
   * <ObfuscatedText text="1,000 users" length={5} />
   * <ObfuscatedText text="Secret data" animate={false} />
   * <ObfuscatedText text="API Key" charset="glitch" color="warning" />
   * <ObfuscatedText text="Hidden" revealOnHover pauseOnHover />
   * ```
   */

  import { onMount, onDestroy } from 'svelte';

  // Character sets
  const CHARS_ENCHANT = 'ᔑᒷᓵᒷ⊣╎⋮ꖌꖎᒲリ𝙹ᑑ∷ᓭℸ∴⨅';
  const CHARS_GLITCH = '█▓▒░╔╗╚╝║═┌┐└┘│─┼▀▄▌▐■□▪▫●○';
  const CHARS_BLOCK = '█▓▒░';
  const CHARS_BINARY = '01';
  const CHARS_HEX = '0123456789ABCDEF';

  type CharsetType = 'enchant' | 'glitch' | 'block' | 'binary' | 'hex';
  type ColorVariant = 'default' | 'info' | 'warning' | 'danger' | 'success';

  export let text: string = ''; // Original text (used to determine length if length prop not provided)
  export let length: number | null = null; // Custom length override
  export let animate: boolean = true; // Whether to animate the scrambling
  export let className: string = ''; // Additional CSS classes
  export let charset: CharsetType = 'enchant'; // Character set to use
  export let color: ColorVariant = 'default'; // Color variant
  export let updateInterval: number = 100; // Update interval in ms
  export let blur: boolean = false; // Apply blur effect
  export let revealOnHover: boolean = false; // Show actual text on hover
  export let pauseOnHover: boolean = false; // Pause animation on hover
  export let ariaLabel: string = ''; // Custom aria-label (defaults to text)

  let displayText: string = '';
  let animationFrame: number | null = null;
  let isAnimating: boolean = false;
  let measureElement: HTMLSpanElement;
  let containerElement: HTMLSpanElement;
  let measuredWidth: number = 0;
  let lastUpdateTime: number = 0;
  let isHovered: boolean = false;
  let isPaused: boolean = false;

  // Get character set based on charset prop
  function getCharset(): string {
    switch (charset) {
      case 'glitch': return CHARS_GLITCH;
      case 'block': return CHARS_BLOCK;
      case 'binary': return CHARS_BINARY;
      case 'hex': return CHARS_HEX;
      case 'enchant':
      default: return CHARS_ENCHANT;
    }
  }

  // Get a random character from the selected charset
  function getRandomChar(): string {
    const charSet = getCharset();
    const chars = [...charSet];
    return chars[Math.floor(Math.random() * chars.length)] || '?';
  }

  // Generate scrambled text
  function generateScrambledText(): string {
    const textLength = length !== null ? length : [...text].length;
    return Array.from({ length: textLength }, () => getRandomChar()).join('');
  }

  // Measure the actual width of the original text
  function measureOriginalTextWidth(): void {
    if (measureElement) {
      // Force a layout to get accurate measurement
      measuredWidth = measureElement.offsetWidth;
    }
  }

  // Animation loop - updates scrambled text based on time interval
  function animateScramble(timestamp: number): void {
    if (!animate || !isAnimating || isPaused) return;
    
    // Only update if enough time has passed since last update
    if (timestamp - lastUpdateTime >= updateInterval) {
      displayText = generateScrambledText();
      lastUpdateTime = timestamp;
    }
    
    animationFrame = requestAnimationFrame(animateScramble);
  }

  // Handle mouse enter
  function handleMouseEnter(): void {
    isHovered = true;
    if (pauseOnHover) {
      isPaused = true;
    }
  }

  // Handle mouse leave
  function handleMouseLeave(): void {
    isHovered = false;
    if (pauseOnHover) {
      isPaused = false;
    }
  }

  // Handle copy event - copy actual text instead of scrambled
  function handleCopy(event: ClipboardEvent): void {
    if (text) {
      event.preventDefault();
      event.clipboardData?.setData('text/plain', text);
    }
  }

  // Start animation
  function startAnimation(): void {
    if (!animate) {
      displayText = generateScrambledText();
      return;
    }

    lastUpdateTime = 0;
    isAnimating = true;
    requestAnimationFrame(animateScramble);
  }

  // Stop animation
  function stopAnimation(): void {
    isAnimating = false;
    if (animationFrame !== null) {
      cancelAnimationFrame(animationFrame);
      animationFrame = null;
    }
  }

  onMount(() => {
    measureOriginalTextWidth();
    startAnimation();
  });

  onDestroy(() => {
    stopAnimation();
  });

  // Restart animation if props change
  $: if (text || length !== null || charset) {
    measureOriginalTextWidth();
    stopAnimation();
    startAnimation();
  }

  // Determine what text to show
  $: actualDisplayText = (revealOnHover && isHovered) ? text : displayText;
  
  // Computed aria-label
  $: computedAriaLabel = ariaLabel || text || 'Obfuscated text';

  // Generate placeholder text for width measurement (same length as obfuscated text)
  $: placeholderText = length !== null 
    ? '0'.repeat(length) 
    : text || '0'.repeat(5);
</script>

<!-- Hidden element to measure original text width -->
<span bind:this={measureElement} class="measure-text" aria-hidden="true">
  {placeholderText}
</span>

<!-- Visible obfuscated text with fixed width -->
<span 
  bind:this={containerElement}
  class="obfuscated-text {className}" 
  class:animated={animate}
  class:blur={blur}
  class:color-info={color === 'info'}
  class:color-warning={color === 'warning'}
  class:color-danger={color === 'danger'}
  class:color-success={color === 'success'}
  class:reveal-hover={revealOnHover}
  style="width: {measuredWidth}px;"
  aria-label={computedAriaLabel}
  role="text"
  on:mouseenter={handleMouseEnter}
  on:mouseleave={handleMouseLeave}
  on:copy={handleCopy}
>
  {actualDisplayText}
</span>

<style lang="scss">
  @use '../../shared-styles/mixins' as *;

  .measure-text {
    position: absolute;
    visibility: hidden;
    pointer-events: none;
    white-space: nowrap;
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    letter-spacing: inherit;
    line-height: inherit;
  }

  .obfuscated-text {
    @include text-obfuscate-static;
    display: inline-block;
    font-variant: normal;
    font-feature-settings: normal;
    user-select: none;
    pointer-events: none;
    text-align: center;
    vertical-align: baseline;
    overflow: hidden;
    white-space: nowrap;
    box-sizing: border-box;
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    line-height: 1;
    position: relative;
    top: 0;
  }

  .obfuscated-text.animated {
    @include text-obfuscate(1.6s);
  }

  // Blur effect
  .obfuscated-text.blur {
    filter: blur(1px);
  }

  // Color variants
  .obfuscated-text.color-info {
    color: var(--info);
  }

  .obfuscated-text.color-warning {
    color: var(--warning);
  }

  .obfuscated-text.color-danger {
    color: var(--danger);
  }

  .obfuscated-text.color-success {
    color: var(--success);
  }

  // Reveal on hover
  .obfuscated-text.reveal-hover {
    cursor: help;
    transition: opacity 0.3s ease;
  }

  .obfuscated-text.reveal-hover:hover {
    opacity: 1;
  }
</style>

// packages/shared-components/react/ObfuscatedText.tsx
/**
 * ObfuscatedText Component (React - Enhanced)
 * 
 * A reusable component for displaying obfuscated/scrambled text using various character sets.
 * Perfect for hiding undecided values, redacting sensitive information, or creating mysterious text effects.
 * 
 * @example
 * ```tsx
 * <ObfuscatedText text="$99.99" />
 * <ObfuscatedText text="1,000 users" length={5} />
 * <ObfuscatedText text="Secret data" animate={false} />
 * <ObfuscatedText text="API Key" charset="glitch" color="warning" />
 * <ObfuscatedText text="Hidden" revealOnHover pauseOnHover />
 * ```
 */

import React, { useEffect, useRef, useState, useCallback, useMemo } from 'react';
import './ObfuscatedText.scss';

// Character sets
const CHARS_ENCHANT = 'ᔑᒷᓵᒷ⊣╎⋮ꖌꖎᒲリ𝙹ᑑ∷ᓭℸ∴⨅';
const CHARS_GLITCH = '█▓▒░╔╗╚╝║═┌┐└┘│─┼▀▄▌▐■□▪▫●○';
const CHARS_BLOCK = '█▓▒░';
const CHARS_BINARY = '01';
const CHARS_HEX = '0123456789ABCDEF';

type CharsetType = 'enchant' | 'glitch' | 'block' | 'binary' | 'hex';
type ColorVariant = 'default' | 'info' | 'warning' | 'danger' | 'success';

interface ObfuscatedTextProps {
  text?: string; // Original text (used to determine length if length prop not provided)
  length?: number | null; // Custom length override
  animate?: boolean; // Whether to animate the scrambling
  className?: string; // Additional CSS classes
  charset?: CharsetType; // Character set to use
  color?: ColorVariant; // Color variant
  updateInterval?: number; // Update interval in ms
  blur?: boolean; // Apply blur effect
  revealOnHover?: boolean; // Show actual text on hover
  pauseOnHover?: boolean; // Pause animation on hover
  ariaLabel?: string; // Custom aria-label (defaults to text)
}

export const ObfuscatedText: React.FC<ObfuscatedTextProps> = ({
  text = '',
  length = null,
  animate = true,
  className = '',
  charset = 'enchant',
  color = 'default',
  updateInterval = 100,
  blur = false,
  revealOnHover = false,
  pauseOnHover = false,
  ariaLabel = '',
}) => {
  const [displayText, setDisplayText] = useState<string>('');
  const [measuredWidth, setMeasuredWidth] = useState<number>(0);
  const [isHovered, setIsHovered] = useState<boolean>(false);
  
  const measureRef = useRef<HTMLSpanElement>(null);
  const animationFrameRef = useRef<number | null>(null);
  const lastUpdateTimeRef = useRef<number>(0);
  const isAnimatingRef = useRef<boolean>(false);
  const isPausedRef = useRef<boolean>(false);

  // Get character set based on charset prop
  const getCharset = useMemo((): string => {
    switch (charset) {
      case 'glitch': return CHARS_GLITCH;
      case 'block': return CHARS_BLOCK;
      case 'binary': return CHARS_BINARY;
      case 'hex': return CHARS_HEX;
      case 'enchant':
      default: return CHARS_ENCHANT;
    }
  }, [charset]);

  // Get a random character from the selected charset
  const getRandomChar = useCallback((): string => {
    const chars = [...getCharset];
    return chars[Math.floor(Math.random() * chars.length)] || '?';
  }, [getCharset]);

  // Generate scrambled text
  const generateScrambledText = useCallback((): string => {
    const textLength = length !== null ? length : [...text].length;
    return Array.from({ length: textLength }, () => getRandomChar()).join('');
  }, [length, text, getRandomChar]);

  // Measure the actual width of the original text
  const measureOriginalTextWidth = useCallback((): void => {
    if (measureRef.current) {
      setMeasuredWidth(measureRef.current.offsetWidth);
    }
  }, []);

  // Animation loop - updates scrambled text based on time interval
  const animateScramble = useCallback((timestamp: number): void => {
    if (!animate || !isAnimatingRef.current || isPausedRef.current) return;

    // Only update if enough time has passed since last update
    if (timestamp - lastUpdateTimeRef.current >= updateInterval) {
      setDisplayText(generateScrambledText());
      lastUpdateTimeRef.current = timestamp;
    }

    animationFrameRef.current = requestAnimationFrame(animateScramble);
  }, [animate, generateScrambledText, updateInterval]);

  // Start animation
  const startAnimation = useCallback((): void => {
    if (!animate) {
      setDisplayText(generateScrambledText());
      return;
    }

    lastUpdateTimeRef.current = 0;
    isAnimatingRef.current = true;
    animationFrameRef.current = requestAnimationFrame(animateScramble);
  }, [animate, generateScrambledText, animateScramble]);

  // Stop animation
  const stopAnimation = useCallback((): void => {
    isAnimatingRef.current = false;
    if (animationFrameRef.current !== null) {
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = null;
    }
  }, []);

  // Handle mouse enter
  const handleMouseEnter = useCallback((): void => {
    setIsHovered(true);
    if (pauseOnHover) {
      isPausedRef.current = true;
    }
  }, [pauseOnHover]);

  // Handle mouse leave
  const handleMouseLeave = useCallback((): void => {
    setIsHovered(false);
    if (pauseOnHover) {
      isPausedRef.current = false;
    }
  }, [pauseOnHover]);

  // Handle copy event - copy actual text instead of scrambled
  const handleCopy = useCallback((event: React.ClipboardEvent<HTMLSpanElement>): void => {
    if (text) {
      event.preventDefault();
      event.clipboardData.setData('text/plain', text);
    }
  }, [text]);

  // Initialize on mount
  useEffect(() => {
    measureOriginalTextWidth();
    startAnimation();

    return () => {
      stopAnimation();
    };
  }, [measureOriginalTextWidth, startAnimation, stopAnimation]);

  // Restart animation if props change
  useEffect(() => {
    measureOriginalTextWidth();
    stopAnimation();
    startAnimation();
  }, [text, length, charset, measureOriginalTextWidth, stopAnimation, startAnimation]);

  // Generate placeholder text for width measurement (same length as obfuscated text)
  const placeholderText = useMemo(() => {
    return length !== null 
      ? '0'.repeat(length) 
      : text || '0'.repeat(5);
  }, [length, text]);

  // Determine what text to show
  const actualDisplayText = useMemo(() => {
    return (revealOnHover && isHovered) ? text : displayText;
  }, [revealOnHover, isHovered, text, displayText]);

  // Computed aria-label
  const computedAriaLabel = useMemo(() => {
    return ariaLabel || text || 'Obfuscated text';
  }, [ariaLabel, text]);

  // Build class names
  const classNames = useMemo(() => {
    const classes = ['obfuscated-text'];
    if (animate) classes.push('animated');
    if (blur) classes.push('blur');
    if (color !== 'default') classes.push(`color-${color}`);
    if (revealOnHover) classes.push('reveal-hover');
    if (className) classes.push(className);
    return classes.join(' ');
  }, [animate, blur, color, revealOnHover, className]);

  return (
    <>
      {/* Hidden element to measure original text width */}
      <span ref={measureRef} className="measure-text" aria-hidden="true">
        {placeholderText}
      </span>

      {/* Visible obfuscated text with fixed width */}
      <span
        className={classNames}
        style={{ width: `${measuredWidth}px` }}
        aria-label={computedAriaLabel}
        role="text"
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onCopy={handleCopy}
      >
        {actualDisplayText}
      </span>
    </>
  );
};

export default ObfuscatedText;
