// mods-hub/src/components/common/Tooltip.tsx
/**
 * Tooltip Component
 * 
 * Portal-enabled tooltip component that prevents content shift and ensures
 * tooltip stays within viewport bounds. Matches main app's smart tooltip behavior.
 * 
 * @example
 * <Tooltip text="Click to copy">
 *   <button>Copy</button>
 * </Tooltip>
 */

import { useState, useRef, useEffect, useCallback, ReactNode } from 'react';
import { createPortal } from 'react-dom';
import styled, { css } from 'styled-components';
import { colors, spacing } from '../../theme';

type TooltipPosition = 'top' | 'bottom' | 'left' | 'right' | 'auto';

interface TooltipProps {
  text: string;
  position?: TooltipPosition;
  delay?: number;
  disabled?: boolean;
  maxWidth?: string | null;
  children: ReactNode;
}

const TooltipWrapper = styled.div`
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
`;

const TooltipElement = styled.div<{ 
  $position: 'top' | 'bottom' | 'left' | 'right';
  $maxWidth?: string;
}>`
  position: fixed;
  z-index: 100002; /* Highest - above modals and toasts */
  padding: 6px 10px;
  background: var(--card, ${colors.bgSecondary});
  border: 1px solid var(--border, ${colors.border});
  color: var(--text, ${colors.text});
  font-size: 0.85em;
  line-height: 1.4;
  pointer-events: none;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  border-radius: 4px;
  white-space: normal;
  word-wrap: break-word;
  overflow-wrap: break-word;
  text-align: center;
  display: inline-block;
  max-width: ${props => props.$maxWidth || '300px'};
  min-width: 200px;
  
  /* Arrow styles */
  &::after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
  }
  
  &::before {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
    z-index: -1;
  }
  
  /* Top position - arrow points down */
  ${props => props.$position === 'top' && css`
    &::after {
      top: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 5px 5px 0 5px;
      border-color: var(--card, ${colors.bgSecondary}) transparent transparent transparent;
    }
    
    &::before {
      top: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 6px 6px 0 6px;
      border-color: var(--border, ${colors.border}) transparent transparent transparent;
      margin-top: -1px;
    }
  `}
  
  /* Bottom position - arrow points up */
  ${props => props.$position === 'bottom' && css`
    &::after {
      bottom: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 0 5px 5px 5px;
      border-color: transparent transparent var(--card, ${colors.bgSecondary}) transparent;
    }
    
    &::before {
      bottom: 100%;
      left: 50%;
      transform: translateX(-50%);
      border-width: 0 6px 6px 6px;
      border-color: transparent transparent var(--border, ${colors.border}) transparent;
      margin-bottom: -1px;
    }
  `}
  
  /* Left position - arrow points right */
  ${props => props.$position === 'left' && css`
    &::after {
      left: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 5px 0 5px 5px;
      border-color: transparent transparent transparent var(--card, ${colors.bgSecondary});
    }
    
    &::before {
      left: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 6px 0 6px 6px;
      border-color: transparent transparent transparent var(--border, ${colors.border});
      margin-left: -1px;
    }
  `}
  
  /* Right position - arrow points left */
  ${props => props.$position === 'right' && css`
    &::after {
      right: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 5px 5px 5px 0;
      border-color: transparent var(--card, ${colors.bgSecondary}) transparent transparent;
    }
    
    &::before {
      right: 100%;
      top: 50%;
      transform: translateY(-50%);
      border-width: 6px 6px 6px 0;
      border-color: transparent var(--border, ${colors.border}) transparent transparent;
      margin-right: -1px;
    }
  `}
`;

export function Tooltip({ 
  text, 
  position = 'auto', 
  delay = 0, 
  disabled = false,
  maxWidth = null,
  children 
}: TooltipProps) {
  const [show, setShow] = useState(false);
  const [actualPosition, setActualPosition] = useState<'top' | 'bottom' | 'left' | 'right'>('top');
  const [tooltipStyle, setTooltipStyle] = useState<React.CSSProperties>({});
  const wrapperRef = useRef<HTMLDivElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);
  const portalContainerRef = useRef<HTMLDivElement | null>(null);
  const hoverTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const listenersActiveRef = useRef(false);

  // Calculate max width based on viewport
  const calculateMaxWidth = useCallback((): string => {
    if (maxWidth !== null) {
      return maxWidth;
    }
    if (typeof window === 'undefined') return '300px';
    const viewportWidth = window.innerWidth;
    const calculated = Math.max(200, Math.min(500, Math.floor(viewportWidth * 0.4)));
    return `${calculated}px`;
  }, [maxWidth]);

  // Calculate best position based on available space
  const calculatePosition = useCallback((): 'top' | 'bottom' | 'left' | 'right' => {
    if (position !== 'auto') {
      return position;
    }

    if (!wrapperRef.current || !tooltipRef.current) {
      return 'top';
    }

    const triggerRect = wrapperRef.current.getBoundingClientRect();
    const tooltipRect = tooltipRef.current.getBoundingClientRect();
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;

    // Check available space in each direction
    const spaceTop = triggerRect.top;
    const spaceBottom = viewportHeight - triggerRect.bottom;
    const spaceLeft = triggerRect.left;
    const spaceRight = viewportWidth - triggerRect.right;

    // Determine best position
    if (spaceBottom >= tooltipRect.height + 10) {
      return 'bottom';
    } else if (spaceTop >= tooltipRect.height + 10) {
      return 'top';
    } else if (spaceRight >= tooltipRect.width + 10) {
      return 'right';
    } else if (spaceLeft >= tooltipRect.width + 10) {
      return 'left';
    } else {
      return 'bottom'; // Default fallback
    }
  }, [position]);

  // Update tooltip position using fixed positioning
  const updateTooltipPosition = useCallback(() => {
    if (!wrapperRef.current || !tooltipRef.current) return;

    const triggerRect = wrapperRef.current.getBoundingClientRect();
    const tooltipRect = tooltipRef.current.getBoundingClientRect();
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;

    let top = 0;
    let left = 0;
    const padding = 8;

    switch (actualPosition) {
      case 'top':
        top = triggerRect.top - tooltipRect.height - padding;
        left = triggerRect.left + (triggerRect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'bottom':
        top = triggerRect.bottom + padding;
        left = triggerRect.left + (triggerRect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'left':
        top = triggerRect.top + (triggerRect.height / 2) - (tooltipRect.height / 2);
        left = triggerRect.left - tooltipRect.width - padding;
        break;
      case 'right':
        top = triggerRect.top + (triggerRect.height / 2) - (tooltipRect.height / 2);
        left = triggerRect.right + padding;
        break;
    }

    // Keep tooltip within viewport bounds
    if (left < padding) left = padding;
    if (left + tooltipRect.width > viewportWidth - padding) {
      left = viewportWidth - tooltipRect.width - padding;
    }
    if (top < padding) top = padding;
    if (top + tooltipRect.height > viewportHeight - padding) {
      top = viewportHeight - tooltipRect.height - padding;
    }

    setTooltipStyle({
      top: `${top}px`,
      left: `${left}px`,
      maxWidth: calculateMaxWidth(),
    });
  }, [actualPosition, calculateMaxWidth]);

  // Handle resize and scroll events
  const handleResize = useCallback(() => {
    if (show && tooltipRef.current) {
      const newPosition = calculatePosition();
      setActualPosition(newPosition);
      updateTooltipPosition();
    }
  }, [show, calculatePosition, updateTooltipPosition]);

  // Show tooltip
  const handleMouseEnter = useCallback(() => {
    if (disabled || !text) return;

    if (delay > 0) {
      hoverTimeoutRef.current = setTimeout(() => {
        setShow(true);
        hoverTimeoutRef.current = null;
      }, delay);
    } else {
      setShow(true);
    }
  }, [disabled, text, delay]);

  // Hide tooltip
  const handleMouseLeave = useCallback(() => {
    if (hoverTimeoutRef.current) {
      clearTimeout(hoverTimeoutRef.current);
      hoverTimeoutRef.current = null;
    }
    setShow(false);
  }, []);

  // Create portal container on mount
  useEffect(() => {
    if (typeof document === 'undefined') return;

    const portalContainer = document.createElement('div');
    portalContainer.id = `tooltip-portal-${Math.random().toString(36).substr(2, 9)}`;
    portalContainer.style.position = 'fixed';
    portalContainer.style.top = '0';
    portalContainer.style.left = '0';
    portalContainer.style.width = '0';
    portalContainer.style.height = '0';
    portalContainer.style.pointerEvents = 'none';
    portalContainer.style.zIndex = '100002';
    document.body.appendChild(portalContainer);
    portalContainerRef.current = portalContainer;

    return () => {
      if (portalContainerRef.current && portalContainerRef.current.parentNode) {
        portalContainerRef.current.parentNode.removeChild(portalContainerRef.current);
      }
    };
  }, []);

  // Update position when tooltip becomes visible
  useEffect(() => {
    if (show && tooltipRef.current && wrapperRef.current) {
      // Wait for tooltip to render, then calculate position
      requestAnimationFrame(() => {
        if (!tooltipRef.current || !wrapperRef.current) return;
        
        const newPosition = calculatePosition();
        setActualPosition(newPosition);
        updateTooltipPosition();

        // Add event listeners if not already active
        if (!listenersActiveRef.current) {
          window.addEventListener('resize', handleResize);
          window.addEventListener('scroll', handleResize, true);
          listenersActiveRef.current = true;
        }
      });
    }

    return () => {
      if (!show && listenersActiveRef.current) {
        window.removeEventListener('resize', handleResize);
        window.removeEventListener('scroll', handleResize, true);
        listenersActiveRef.current = false;
      }
    };
  }, [show, calculatePosition, updateTooltipPosition, handleResize]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (hoverTimeoutRef.current) {
        clearTimeout(hoverTimeoutRef.current);
      }
      if (listenersActiveRef.current) {
        window.removeEventListener('resize', handleResize);
        window.removeEventListener('scroll', handleResize, true);
      }
    };
  }, [handleResize]);

  if (!text || disabled) {
    return <>{children}</>;
  }

  return (
    <>
      <TooltipWrapper
        ref={wrapperRef}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        {children}
      </TooltipWrapper>
      {show && portalContainerRef.current && createPortal(
        <TooltipElement
          ref={tooltipRef}
          $position={actualPosition}
          $maxWidth={calculateMaxWidth()}
          style={tooltipStyle}
          role="tooltip"
        >
          {text}
        </TooltipElement>,
        portalContainerRef.current
      )}
    </>
  );
}

// src/components/Tooltip.svelte
<script lang="ts">
  /**
   * Tooltip Component
   * 
   * Agnostic, reusable tooltip component that shows instantly on hover.
   * Handles positioning automatically based on available space.
   * 
   * @example
   * <Tooltip text="Click me">
   *   <button>Hover me</button>
   * </Tooltip>
   * 
   * @example
   * <Tooltip text="Custom tooltip" position="bottom" delay={0}>
   *   <span>Hover target</span>
   * </Tooltip>
   */
  
  import { onMount, onDestroy } from 'svelte';
  
  // Portal action to render tooltip at body level
  function portal(node: HTMLElement, target: HTMLElement) {
    target.appendChild(node);
    return {
      update(newTarget: HTMLElement) {
        if (newTarget !== target) {
          newTarget.appendChild(node);
          target = newTarget;
        }
      },
      destroy() {
        if (node.parentNode) {
          node.parentNode.removeChild(node);
        }
      }
    };
  }
  
  // Props
  export let text: string = '';
  export let position: 'top' | 'bottom' | 'left' | 'right' | 'auto' = 'auto';
  export let delay: number = 0; // Instant by default
  export let disabled: boolean = false;
  export let maxWidth: string = '200px';
  
  // Internal state
  let show = false;
  let tooltipElement: HTMLDivElement;
  let triggerElement: HTMLElement;
  let actualPosition: 'top' | 'bottom' | 'left' | 'right' = position === 'auto' ? 'top' : position;
  let tooltipId = `tooltip-${Math.random().toString(36).substr(2, 9)}`;
  let hoverTimeout: ReturnType<typeof setTimeout> | null = null;
  let mouseX = 0;
  let mouseY = 0;
  let listenersActive = false;
  let portalContainer: HTMLDivElement | null = null;
  
  // Calculate position based on available space
  function calculatePosition(): void {
    if (!tooltipElement || !triggerElement) return;
    
    if (position !== 'auto') {
      actualPosition = position;
      updateTooltipPosition();
      return;
    }
    
    const triggerRect = triggerElement.getBoundingClientRect();
    const tooltipRect = tooltipElement.getBoundingClientRect();
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;
    
    // Check available space in each direction
    const spaceTop = triggerRect.top;
    const spaceBottom = viewportHeight - triggerRect.bottom;
    const spaceLeft = triggerRect.left;
    const spaceRight = viewportWidth - triggerRect.right;
    
    // Determine best position
    if (spaceBottom >= tooltipRect.height + 10) {
      actualPosition = 'bottom';
    } else if (spaceTop >= tooltipRect.height + 10) {
      actualPosition = 'top';
    } else if (spaceRight >= tooltipRect.width + 10) {
      actualPosition = 'right';
    } else if (spaceLeft >= tooltipRect.width + 10) {
      actualPosition = 'left';
    } else {
      // Default to bottom if no space available
      actualPosition = 'bottom';
    }
    
    updateTooltipPosition();
  }
  
  // Update tooltip position using fixed positioning
  function updateTooltipPosition(): void {
    if (!tooltipElement || !triggerElement) return;
    
    const triggerRect = triggerElement.getBoundingClientRect();
    const tooltipRect = tooltipElement.getBoundingClientRect();
    
    let top = 0;
    let left = 0;
    
    switch (actualPosition) {
      case 'top':
        top = triggerRect.top - tooltipRect.height - 8;
        left = triggerRect.left + (triggerRect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'bottom':
        top = triggerRect.bottom + 8;
        left = triggerRect.left + (triggerRect.width / 2) - (tooltipRect.width / 2);
        break;
      case 'left':
        top = triggerRect.top + (triggerRect.height / 2) - (tooltipRect.height / 2);
        left = triggerRect.left - tooltipRect.width - 8;
        break;
      case 'right':
        top = triggerRect.top + (triggerRect.height / 2) - (tooltipRect.height / 2);
        left = triggerRect.right + 8;
        break;
    }
    
    // Keep tooltip within viewport bounds
    const padding = 8;
    if (left < padding) left = padding;
    if (left + tooltipRect.width > window.innerWidth - padding) {
      left = window.innerWidth - tooltipRect.width - padding;
    }
    if (top < padding) top = padding;
    if (top + tooltipRect.height > window.innerHeight - padding) {
      top = window.innerHeight - tooltipRect.height - padding;
    }
    
    tooltipElement.style.top = `${top}px`;
    tooltipElement.style.left = `${left}px`;
  }
  
  // Show tooltip
  function handleMouseEnter(): void {
    if (disabled || !text) return;
    
    if (delay > 0) {
      hoverTimeout = setTimeout(() => {
        show = true;
        hoverTimeout = null;
      }, delay);
    } else {
      show = true;
    }
  }
  
  // Hide tooltip
  function handleMouseLeave(): void {
    if (hoverTimeout) {
      clearTimeout(hoverTimeout);
      hoverTimeout = null;
    }
    show = false;
  }
  
  // Update position when tooltip becomes visible
  $: if (show && tooltipElement && !listenersActive) {
    // Use requestAnimationFrame to ensure DOM is updated
    requestAnimationFrame(() => {
      calculatePosition();
      // Also update on window resize and scroll
      if (!listenersActive) {
        window.addEventListener('resize', updateTooltipPosition);
        window.addEventListener('scroll', updateTooltipPosition, true);
        listenersActive = true;
      }
    });
  }
  
  // Cleanup listeners when tooltip hides
  $: if (!show && listenersActive) {
    window.removeEventListener('resize', updateTooltipPosition);
    window.removeEventListener('scroll', updateTooltipPosition, true);
    listenersActive = false;
  }
  
  // Track mouse position for better positioning
  function handleMouseMove(e: MouseEvent): void {
    mouseX = e.clientX;
    mouseY = e.clientY;
  }
  
  onMount(() => {
    // Create portal container at body level for tooltip
    portalContainer = document.createElement('div');
    portalContainer.id = `tooltip-portal-${tooltipId}`;
    portalContainer.style.position = 'fixed';
    portalContainer.style.top = '0';
    portalContainer.style.left = '0';
    portalContainer.style.width = '0';
    portalContainer.style.height = '0';
    portalContainer.style.pointerEvents = 'none';
    portalContainer.style.zIndex = '99999';
    document.body.appendChild(portalContainer);
    
    // Find the trigger element (first child)
    if (triggerElement) {
      triggerElement.addEventListener('mouseenter', handleMouseEnter);
      triggerElement.addEventListener('mouseleave', handleMouseLeave);
      triggerElement.addEventListener('mousemove', handleMouseMove);
      triggerElement.setAttribute('aria-describedby', tooltipId);
    }
  });
  
  onDestroy(() => {
    if (triggerElement) {
      triggerElement.removeEventListener('mouseenter', handleMouseEnter);
      triggerElement.removeEventListener('mouseleave', handleMouseLeave);
      triggerElement.removeEventListener('mousemove', handleMouseMove);
      triggerElement.removeAttribute('aria-describedby');
    }
    if (hoverTimeout) {
      clearTimeout(hoverTimeout);
    }
    if (listenersActive) {
      window.removeEventListener('resize', updateTooltipPosition);
      window.removeEventListener('scroll', updateTooltipPosition, true);
      listenersActive = false;
    }
    // Clean up portal container
    if (portalContainer && portalContainer.parentNode) {
      portalContainer.parentNode.removeChild(portalContainer);
    }
  });
</script>

<div class="tooltip-wrapper" bind:this={triggerElement}>
  <slot />
</div>

{#if show && text && portalContainer}
  <div
    class="tooltip"
    class:tooltip--top={actualPosition === 'top'}
    class:tooltip--bottom={actualPosition === 'bottom'}
    class:tooltip--left={actualPosition === 'left'}
    class:tooltip--right={actualPosition === 'right'}
    id={tooltipId}
    role="tooltip"
    bind:this={tooltipElement}
    style="max-width: {maxWidth};"
    use:portal={portalContainer}
  >
    {text}
  </div>
{/if}

<style lang="scss">
  @use '../styles/animations' as *;
  
  .tooltip-wrapper {
    position: relative;
    display: inline-flex;
  }
  
  .tooltip {
    position: fixed;
    z-index: 10000;
    padding: 6px 10px;
    background: var(--card);
    border: 1px solid var(--border);
    color: var(--text);
    font-size: 0.85em;
    line-height: 1.4;
    white-space: nowrap;
    pointer-events: none;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
    animation: fade-in 0.1s ease-out;
    @include gpu-accelerated;
    transform: none;
    
    // Top position - arrow points down
    &.tooltip--top {
      &::after {
        content: '';
        position: absolute;
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        border: 5px solid transparent;
        border-top-color: var(--card);
      }
      
      &::before {
        content: '';
        position: absolute;
        top: 100%;
        left: 50%;
        transform: translateX(-50%);
        border: 6px solid transparent;
        border-top-color: var(--border);
        margin-top: -1px;
      }
    }
    
    // Bottom position - arrow points up
    &.tooltip--bottom {
      &::after {
        content: '';
        position: absolute;
        bottom: 100%;
        left: 50%;
        transform: translateX(-50%);
        border: 5px solid transparent;
        border-bottom-color: var(--card);
      }
      
      &::before {
        content: '';
        position: absolute;
        bottom: 100%;
        left: 50%;
        transform: translateX(-50%);
        border: 6px solid transparent;
        border-bottom-color: var(--border);
        margin-bottom: -1px;
      }
    }
    
    // Left position - arrow points right
    &.tooltip--left {
      &::after {
        content: '';
        position: absolute;
        left: 100%;
        top: 50%;
        transform: translateY(-50%);
        border: 5px solid transparent;
        border-left-color: var(--card);
      }
      
      &::before {
        content: '';
        position: absolute;
        left: 100%;
        top: 50%;
        transform: translateY(-50%);
        border: 6px solid transparent;
        border-left-color: var(--border);
        margin-left: -1px;
      }
    }
    
    // Right position - arrow points left
    &.tooltip--right {
      &::after {
        content: '';
        position: absolute;
        right: 100%;
        top: 50%;
        transform: translateY(-50%);
        border: 5px solid transparent;
        border-right-color: var(--card);
      }
      
      &::before {
        content: '';
        position: absolute;
        right: 100%;
        top: 50%;
        transform: translateY(-50%);
        border: 6px solid transparent;
        border-right-color: var(--border);
        margin-right: -1px;
      }
    }
    
    // Allow text wrapping for longer content
    white-space: normal;
    word-wrap: break-word;
    text-align: center;
  }
</style>
