// mods-hub/src/components/layout/Header.tsx
/**
 * Header component
 */

import styled from 'styled-components';
import { Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../stores/auth';
import { colors, spacing } from '../../theme';

const HeaderContainer = styled.header`
  background: ${colors.bgSecondary};
  border-bottom: 1px solid ${colors.border};
  padding: ${spacing.md} ${spacing.xl};
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 100;
`;

const Logo = styled(Link)`
  font-size: 1.5rem;
  font-weight: 700;
  color: ${colors.accent};
  text-decoration: none;
  
  &:hover {
    color: ${colors.accentHover};
  }
`;

const Nav = styled.nav`
  display: flex;
  align-items: center;
  gap: ${spacing.lg};
`;

const NavLink = styled(Link)`
  color: ${colors.textSecondary};
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s ease;
  
  &:hover {
    color: ${colors.text};
  }
`;

const Button = styled.button<{ variant?: 'primary' | 'secondary' }>`
  padding: ${spacing.sm} ${spacing.md};
  border-radius: 4px;
  font-weight: 500;
  transition: all 0.2s ease;
  cursor: pointer;
  
  ${({ variant = 'primary' }) => 
    variant === 'primary' 
      ? `
        background: ${colors.accent};
        color: ${colors.bg};
        
        &:hover {
          background: ${colors.accentHover};
        }
      `
      : `
        background: transparent;
        color: ${colors.text};
        border: 1px solid ${colors.border};
        
        &:hover {
          border-color: ${colors.borderLight};
        }
      `
  }
`;

export function Header() {
    const { isAuthenticated, user, logout } = useAuthStore();
    const navigate = useNavigate();

    const handleLogout = () => {
        logout();
        navigate('/');
    };

    return (
        <HeaderContainer>
            <Logo to="/">Mods Hub</Logo>
            <Nav>
                <NavLink to="/">Browse</NavLink>
                {isAuthenticated ? (
                    <>
                        <NavLink to="/upload">Upload</NavLink>
                        <Button variant="secondary" onClick={handleLogout}>
                            Logout ({user?.email})
                        </Button>
                    </>
                ) : (
                    <Button variant="primary" onClick={() => navigate('/login')}>
                        Login
                    </Button>
                )}
            </Nav>
        </HeaderContainer>
    );
}

// serverless/otp-auth-service/dashboard/src/components/Header.svelte
<script lang="ts">
  import type { User } from '$lib/types';
  import { createEventDispatcher } from 'svelte';

  export let user: User | null = null;

  const dispatch = createEventDispatcher();

  function handleLogout() {
    dispatch('logout');
  }
</script>

<header class="app-header">
  <div class="app-header__content">
    <a href="/" class="app-header__logo">[AUTH] OTP Auth API</a>
    {#if user}
      <div class="app-header__user">
        <span class="app-header__email">{user.email || 'User'}</span>
        <button class="app-header__logout" onclick={handleLogout}>Logout</button>
      </div>
    {/if}
  </div>
</header>

<style>
  .app-header {
    background: var(--card);
    border-bottom: 1px solid var(--border);
    padding: var(--spacing-md) var(--spacing-xl);
    position: sticky;
    top: 0;
    z-index: 100;
    backdrop-filter: blur(10px);
    background: rgba(37, 32, 23, 0.95);
  }

  .app-header__content {
    max-width: 1400px;
    margin: 0 auto;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .app-header__logo {
    font-size: 1.5rem;
    font-weight: 700;
    background: linear-gradient(135deg, var(--accent), var(--accent-light));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    text-decoration: none;
  }

  .app-header__user {
    display: flex;
    align-items: center;
    gap: var(--spacing-md);
  }

  .app-header__email {
    color: var(--text-secondary);
  }

  .app-header__logout {
    padding: var(--spacing-sm) var(--spacing-lg);
    background: transparent;
    border: 2px solid var(--border);
    border-radius: 0;
    color: var(--text);
    font-weight: 600;
    font-size: 0.875rem;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .app-header__logout:hover {
    background: var(--bg-dark);
    border-color: var(--border-light);
  }

  @media (max-width: 768px) {
    .app-header__content {
      flex-direction: column;
      gap: var(--spacing-md);
    }
  }
</style>
