// serverless/otp-auth-service/src/components/Header.svelte
<script lang="ts">
  export let logo: string = '[AUTH] OTP Auth API';
  export let dashboardLink: string = '/dashboard';
  export let getStartedLink: string = '#code-examples';
  export let docsLink: string = '#docs';
</script>

<header class="header">
  <div class="header-content">
    <a href="/" class="logo">{logo}</a>
    <div class="header-actions">
      <a href={dashboardLink} class="btn btn-secondary">Developer Dashboard</a>
      <a href={getStartedLink} class="btn btn-secondary">Get Started</a>
      <a href={docsLink} class="btn btn-primary">Documentation</a>
    </div>
  </div>
</header>

<style>
  .header {
    background: rgba(37, 32, 23, 0.95);
    border-bottom: 1px solid var(--border);
    padding: var(--spacing-md) var(--spacing-xl);
    position: sticky;
    top: 0;
    z-index: 100;
    backdrop-filter: blur(10px);
  }

  .header-content {
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--spacing-lg);
  }

  .logo {
    font-size: 1.5rem;
    font-weight: 700;
    background: linear-gradient(135deg, var(--accent), var(--accent-light));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    text-decoration: none;
    white-space: nowrap;
  }

  .header-actions {
    display: flex;
    gap: var(--spacing-md);
    align-items: center;
    flex-wrap: wrap;
  }

  .btn {
    padding: var(--spacing-sm) var(--spacing-lg);
    border: 3px solid;
    border-radius: 0;
    font-size: 0.875rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    cursor: pointer;
    transition: all 0.1s cubic-bezier(0.4, 0, 0.2, 1);
    text-decoration: none;
    display: inline-block;
    background: transparent;
    color: var(--text);
  }

  .btn-primary {
    background: var(--accent);
    border-color: var(--accent-dark);
    color: #000;
    box-shadow: 0 4px 0 var(--accent-dark);
  }

  .btn-primary:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 6px 0 var(--accent-dark);
  }

  .btn-secondary {
    border-color: var(--border-light);
    color: var(--text);
  }

  .btn-secondary:hover {
    background: var(--border);
    border-color: var(--border-light);
  }

  @media (max-width: 768px) {
    .header-content {
      flex-direction: column;
      align-items: flex-start;
    }

    .header-actions {
      width: 100%;
      justify-content: flex-start;
    }
  }
</style>

// mods-hub/src/components/layout/Header.tsx
/**
 * Header component
 */

import styled from 'styled-components';
import { Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../stores/auth';
import { colors, spacing } from '../../theme';

const HeaderContainer = styled.header`
  background: ${colors.bgSecondary};
  border-bottom: 1px solid ${colors.border};
  padding: ${spacing.md} ${spacing.xl};
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 100;
`;

const Logo = styled(Link)`
  font-size: 1.5rem;
  font-weight: 700;
  color: ${colors.accent};
  text-decoration: none;
  
  &:hover {
    color: ${colors.accentHover};
  }
`;

const Nav = styled.nav`
  display: flex;
  align-items: center;
  gap: ${spacing.lg};
`;

const NavLink = styled(Link)`
  color: ${colors.textSecondary};
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s ease;
  
  &:hover {
    color: ${colors.text};
  }
`;

const Button = styled.button<{ variant?: 'primary' | 'secondary' }>`
  padding: ${spacing.sm} ${spacing.md};
  border-radius: 4px;
  font-weight: 500;
  transition: all 0.2s ease;
  cursor: pointer;
  
  ${({ variant = 'primary' }) => 
    variant === 'primary' 
      ? `
        background: ${colors.accent};
        color: ${colors.bg};
        
        &:hover {
          background: ${colors.accentHover};
        }
      `
      : `
        background: transparent;
        color: ${colors.text};
        border: 1px solid ${colors.border};
        
        &:hover {
          border-color: ${colors.borderLight};
        }
      `
  }
`;

export function Header() {
    const { isAuthenticated, user, logout } = useAuthStore();
    const navigate = useNavigate();

    const handleLogout = () => {
        logout();
        navigate('/');
    };

    return (
        <HeaderContainer>
            <Logo to="/">Mods Hub</Logo>
            <Nav>
                <NavLink to="/">Browse</NavLink>
                {isAuthenticated ? (
                    <>
                        <NavLink to="/upload">Upload</NavLink>
                        <Button variant="secondary" onClick={handleLogout}>
                            Logout ({user?.email})
                        </Button>
                    </>
                ) : (
                    <Button variant="primary" onClick={() => navigate('/login')}>
                        Login
                    </Button>
                )}
            </Nav>
        </HeaderContainer>
    );
}
