// shared-components/otp-login/react/OtpLogin.tsx
/**
 * OTP Login Component - React Wrapper
 * 
 * Reusable email OTP authentication component for React
 * Uses the shared OtpLoginCore for framework-agnostic logic
 */

import type { ChangeEvent, KeyboardEvent } from 'react';
import { useEffect, useRef, useState } from 'react';
import { getOtpEncryptionKey } from '../../../shared-config/otp-encryption';
import { OtpLoginCore, type LoginSuccessData, type OtpLoginConfig, type OtpLoginState } from '../core';
import { OTP_LENGTH, OTP_HTML_PATTERN, OTP_PLACEHOLDER, OTP_LENGTH_DESCRIPTION } from '../../../shared-config/otp-config';

export interface OtpLoginProps {
  apiUrl: string;
  onSuccess: (data: LoginSuccessData) => void;
  onError?: (error: string) => void;
  endpoints?: OtpLoginConfig['endpoints'];
  customHeaders?: OtpLoginConfig['customHeaders'];
  otpEncryptionKey?: string; // CRITICAL: OTP encryption key for encrypting requests
  title?: string;
  subtitle?: string;
  showAsModal?: boolean;
  onClose?: () => void;
}

export function OtpLogin({
  apiUrl,
  onSuccess,
  onError,
  endpoints,
  customHeaders,
  otpEncryptionKey,
  title = 'Sign In',
  subtitle = 'Enter your email to receive a verification code',
  showAsModal = false,
  onClose,
}: OtpLoginProps) {
  const coreRef = useRef<OtpLoginCore | null>(null);
  const [state, setState] = useState<OtpLoginState>({
    step: 'email',
    email: '',
    otp: '',
    loading: false,
    error: null,
    countdown: 0,
    rateLimitResetAt: null,
    rateLimitCountdown: 0,
  });

  useEffect(() => {
    // CRITICAL: Get encryption key - use prop if provided, otherwise use centralized config
    // This ensures we always use VITE_SERVICE_ENCRYPTION_KEY consistently across the codebase
    const encryptionKey = otpEncryptionKey || getOtpEncryptionKey();
    
    // CRITICAL: Verify encryption key is provided
    if (!encryptionKey) {
      console.error('[OtpLogin] ❌ CRITICAL ERROR: otpEncryptionKey is missing!');
      console.error('[OtpLogin] This will cause encryption to fail. Key status:', {
        hasKey: !!encryptionKey,
        keyType: typeof encryptionKey,
        keyLength: encryptionKey?.length || 0,
        apiUrl: apiUrl,
        usingCentralizedConfig: !otpEncryptionKey
      });
      if (onError) {
        onError('OTP encryption key is required. Please configure VITE_SERVICE_ENCRYPTION_KEY in your build environment.');
      }
      return;
    }
    
    if (encryptionKey.length < 32) {
      console.error('[OtpLogin] ❌ CRITICAL ERROR: otpEncryptionKey is too short!', {
        keyLength: encryptionKey.length,
        requiredLength: 32
      });
      if (onError) {
        onError('OTP encryption key must be at least 32 characters long.');
      }
      return;
    }
    
    console.log('[OtpLogin] ✅ Encryption key provided, length:', encryptionKey.length, otpEncryptionKey ? '(from prop)' : '(from VITE_SERVICE_ENCRYPTION_KEY)');
    
    // Initialize core
    const core = new OtpLoginCore({
      apiUrl,
      onSuccess,
      onError,
      endpoints,
      customHeaders,
      otpEncryptionKey: encryptionKey, // CRITICAL: Pass encryption key for encrypting OTP requests
    });

    coreRef.current = core;

    // Subscribe to state changes
    const unsubscribe = core.subscribe((newState) => {
      setState(newState);
    });

    // Cleanup on unmount
    return () => {
      unsubscribe();
      core.destroy();
    };
  }, [apiUrl, onSuccess, onError, endpoints, customHeaders, otpEncryptionKey]); // Note: getOtpEncryptionKey() is stable, so we don't need it in deps

  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
    coreRef.current?.setEmail(e.target.value);
  };

  const handleOtpChange = (e: ChangeEvent<HTMLInputElement>) => {
    coreRef.current?.setOtp(e.target.value);
  };

  const handleRequestOtp = () => {
    coreRef.current?.requestOtp();
  };

  const handleVerifyOtp = () => {
    coreRef.current?.verifyOtp();
  };

  const handleGoBack = () => {
    coreRef.current?.goBack();
  };

  const handleKeyPress = (e: KeyboardEvent, handler: () => void) => {
    if (e.key === 'Enter' && !state.loading) {
      handler();
    }
  };

  const formatCountdown = (seconds: number): string => {
    return OtpLoginCore.formatCountdown(seconds);
  };

  if (showAsModal) {
    return (
      <div
        className="otp-login-modal-overlay"
        onClick={onClose}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === 'Escape' && onClose?.()}
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'rgba(0, 0, 0, 0.7)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1000000,
        }}
      >
        <div
          className="otp-login-modal"
          onClick={(e) => e.stopPropagation()}
          onKeyDown={(e) => e.stopPropagation()}
          role="dialog"
          aria-labelledby="otp-login-title"
          tabIndex={-1}
          style={{
            background: 'var(--card, #fff)',
            border: '1px solid var(--border, #ddd)',
            borderRadius: '12px',
            width: '90%',
            maxWidth: 'min(90vw, 500px)',
            maxHeight: '90vh',
            overflowY: 'auto',
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
          }}
        >
          <div
            className="otp-login-header"
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '24px',
              borderBottom: '1px solid var(--border, #ddd)',
            }}
          >
            <h2 id="otp-login-title" style={{ margin: 0, fontSize: '24px' }}>
              {title}
            </h2>
            {onClose && (
              <button
                type="button"
                className="otp-login-close"
                onClick={(e) => {
                  e.stopPropagation();
                  onClose();
                }}
                aria-label="Close"
                style={{
                  background: 'none',
                  border: 'none',
                  fontSize: '32px',
                  cursor: 'pointer',
                  padding: 0,
                  width: '32px',
                  height: '32px',
                }}
              >
                ×
              </button>
            )}
          </div>
          <div className="otp-login-content" style={{ padding: '24px' }}>
            {state.error && (
              <div style={{ color: 'var(--danger, #f00)', marginBottom: '16px', textAlign: 'center' }}>
                {state.error}
              </div>
            )}
            {state.step === 'email' ? (
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleRequestOtp();
                }}
                style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
              >
                <div>
                  <label htmlFor="otp-login-email" style={{ display: 'block', marginBottom: '8px' }}>
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="otp-login-email"
                    value={state.email}
                    onChange={handleEmailChange}
                    onKeyDown={(e) => handleKeyPress(e, handleRequestOtp)}
                    disabled={state.loading}
                    required
                    style={{
                      width: '100%',
                      padding: '12px',
                      border: '1px solid var(--border, #ddd)',
                      borderRadius: '4px',
                      fontSize: '16px',
                    }}
                  />
                </div>
                <button
                  type="submit"
                  disabled={state.loading}
                  style={{
                    padding: '12px 24px',
                    background: state.loading ? 'var(--border, #ddd)' : 'var(--accent, #007bff)',
                    color: '#fff',
                    border: 'none',
                    borderRadius: '4px',
                    cursor: state.loading ? 'not-allowed' : 'pointer',
                    fontSize: '16px',
                    fontWeight: 500,
                  }}
                >
                  {state.loading ? 'Sending...' : 'Send OTP'}
                </button>
              </form>
            ) : (
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleVerifyOtp();
                }}
                style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
              >
                <div style={{ textAlign: 'center', color: 'var(--text-secondary, #666)', marginBottom: '16px' }}>
                  Check your email for the OTP code
                </div>
                <div>
                  <label htmlFor="otp-login-otp" style={{ display: 'block', marginBottom: '8px' }}>
                    {OTP_LENGTH_DESCRIPTION} OTP Code
                  </label>
                  <input
                    type="tel"
                    id="otp-login-otp"
                    value={state.otp}
                    onChange={handleOtpChange}
                    onKeyDown={(e) => handleKeyPress(e, handleVerifyOtp)}
                    disabled={state.loading}
                    required
                    maxLength={OTP_LENGTH}
                    pattern={OTP_HTML_PATTERN}
                    inputMode="numeric"
                    autoComplete="one-time-code"
                    placeholder={OTP_PLACEHOLDER}
                    style={{
                      width: '100%',
                      padding: '12px',
                      border: '1px solid var(--border, #ddd)',
                      borderRadius: '4px',
                      fontSize: '16px',
                      textAlign: 'center',
                      letterSpacing: '8px',
                    }}
                  />
                  {state.countdown > 0 && (
                    <div style={{ marginTop: '8px', fontSize: '14px', color: 'var(--text-secondary, #666)' }}>
                      Code expires in: {formatCountdown(state.countdown)}
                    </div>
                  )}
                </div>
                <button
                  type="submit"
                  disabled={state.loading}
                  style={{
                    padding: '12px 24px',
                    background: state.loading ? 'var(--border, #ddd)' : 'var(--accent, #007bff)',
                    color: '#fff',
                    border: 'none',
                    borderRadius: '4px',
                    cursor: state.loading ? 'not-allowed' : 'pointer',
                    fontSize: '16px',
                    fontWeight: 500,
                  }}
                >
                  {state.loading ? 'Verifying...' : 'Verify OTP'}
                </button>
                <button
                  type="button"
                  onClick={handleGoBack}
                  disabled={state.loading}
                  style={{
                    padding: '12px 24px',
                    background: 'transparent',
                    color: 'var(--text, #000)',
                    border: '1px solid var(--border, #ddd)',
                    borderRadius: '4px',
                    cursor: state.loading ? 'not-allowed' : 'pointer',
                    fontSize: '16px',
                  }}
                >
                  Back
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className="otp-login"
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        padding: '24px',
      }}
    >
      <div
        className="otp-login-container"
        style={{
          maxWidth: '400px',
          width: '100%',
        }}
      >
        <div className="otp-login-header" style={{ textAlign: 'center', marginBottom: '32px' }}>
          <h1 className="otp-login-title" style={{ fontSize: '2rem', marginBottom: '16px' }}>
            {title}
          </h1>
          <p className="otp-login-subtitle" style={{ color: 'var(--text-secondary, #666)' }}>
            {subtitle}
          </p>
        </div>
        {state.error && (
          <div style={{ color: 'var(--danger, #f00)', marginBottom: '16px', textAlign: 'center' }}>
            {state.error}
          </div>
        )}
        {state.step === 'email' ? (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleRequestOtp();
            }}
            style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
          >
            <input
              type="email"
              placeholder="Email address"
              value={state.email}
              onChange={handleEmailChange}
              onKeyDown={(e) => handleKeyPress(e, handleRequestOtp)}
              disabled={state.loading}
              required
              style={{
                padding: '12px',
                border: '1px solid var(--border, #ddd)',
                borderRadius: '4px',
                fontSize: '16px',
              }}
            />
            <button
              type="submit"
              disabled={state.loading}
              style={{
                padding: '12px 24px',
                background: state.loading ? 'var(--border, #ddd)' : 'var(--accent, #007bff)',
                color: '#fff',
                border: 'none',
                borderRadius: '4px',
                cursor: state.loading ? 'not-allowed' : 'pointer',
                fontSize: '16px',
                fontWeight: 500,
              }}
            >
              {state.loading ? 'Sending...' : 'Send OTP'}
            </button>
          </form>
        ) : (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleVerifyOtp();
            }}
            style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
          >
            <div style={{ textAlign: 'center', color: 'var(--text-secondary, #666)', marginBottom: '16px' }}>
              Check your email for the OTP code
            </div>
            <input
              type="tel"
              placeholder={OTP_PLACEHOLDER}
              value={state.otp}
              onChange={handleOtpChange}
              onKeyDown={(e) => handleKeyPress(e, handleVerifyOtp)}
              disabled={state.loading}
              required
              maxLength={OTP_LENGTH}
              pattern={OTP_HTML_PATTERN}
              inputMode="numeric"
              autoComplete="one-time-code"
              style={{
                padding: '12px',
                border: '1px solid var(--border, #ddd)',
                borderRadius: '4px',
                fontSize: '16px',
                textAlign: 'center',
                letterSpacing: '8px',
              }}
            />
            {state.countdown > 0 && (
              <div style={{ fontSize: '14px', color: 'var(--text-secondary, #666)', textAlign: 'center' }}>
                Code expires in: {formatCountdown(state.countdown)}
              </div>
            )}
            <button
              type="submit"
              disabled={state.loading}
              style={{
                padding: '12px 24px',
                background: state.loading ? 'var(--border, #ddd)' : 'var(--accent, #007bff)',
                color: '#fff',
                border: 'none',
                borderRadius: '4px',
                cursor: state.loading ? 'not-allowed' : 'pointer',
                fontSize: '16px',
                fontWeight: 500,
              }}
            >
              {state.loading ? 'Verifying...' : 'Verify OTP'}
            </button>
            <button
              type="button"
              onClick={handleGoBack}
              disabled={state.loading}
              style={{
                padding: '12px 24px',
                background: 'transparent',
                color: 'var(--text, #000)',
                border: '1px solid var(--border, #ddd)',
                borderRadius: '4px',
                cursor: state.loading ? 'not-allowed' : 'pointer',
                fontSize: '16px',
              }}
            >
              Back
            </button>
          </form>
        )}
      </div>
    </div>
  );
}

// packages/otp-login/svelte/OtpLogin.svelte
<svelte:options runes={false} />

<script lang="ts">
  /**
   * OTP Login Component - Svelte Wrapper
   * 
   * Reusable email OTP authentication component for Svelte
   */
  
  import { onDestroy, onMount } from 'svelte';
  import type { OtpLoginState } from '../core';
  import { OtpLoginCore, type LoginSuccessData, type OtpLoginConfig } from '../core';
  import { getOtpEncryptionKey } from '../../../shared-config/otp-encryption';
  import EmailForm from './components/EmailForm.svelte';
  import ErrorDisplay from './components/ErrorDisplay.svelte';
  import OtpForm from './components/OtpForm.svelte';

  export let apiUrl: string;
  export let onSuccess: (data: LoginSuccessData) => void;
  export let onError: ((error: string) => void) | undefined = undefined;
  export let endpoints: OtpLoginConfig['endpoints'] | undefined = undefined;
  export let customHeaders: OtpLoginConfig['customHeaders'] | undefined = undefined;
  export let otpEncryptionKey: string | undefined = undefined; // CRITICAL: OTP encryption key for encrypting requests
  export let title: string = 'Sign In';
  export let subtitle: string = 'Enter your email to receive a verification code';
  export let showAsModal: boolean = false;
  export let onClose: (() => void) | undefined = undefined;

  let core: OtpLoginCore;
  let state: OtpLoginState = {
    step: 'email',
    email: '',
    otp: '',
    loading: false,
    error: null,
    countdown: 0,
    rateLimitResetAt: null,
    rateLimitCountdown: 0,
  };

  // Store unsubscribe function for cleanup
  let unsubscribe: (() => void) | null = null;

  onMount(async () => {
    console.log('[OtpLogin] onMount - showAsModal:', showAsModal);
    
    // CRITICAL: Get encryption key - use prop if provided, otherwise use centralized config
    // This ensures we always use VITE_SERVICE_ENCRYPTION_KEY consistently across the codebase
    const encryptionKey = otpEncryptionKey || getOtpEncryptionKey();
    
    // CRITICAL: Verify encryption key is provided
    if (!encryptionKey) {
      console.error('[OtpLogin] ✗ CRITICAL ERROR: otpEncryptionKey is missing!');
      console.error('[OtpLogin] This will cause encryption to fail. Key status:', {
        hasKey: !!encryptionKey,
        keyType: typeof encryptionKey,
        keyLength: encryptionKey?.length || 0,
        apiUrl: apiUrl,
        usingCentralizedConfig: !otpEncryptionKey
      });
      if (onError) {
        onError('OTP encryption key is required. Please configure VITE_SERVICE_ENCRYPTION_KEY in your build environment.');
      }
      return;
    }
    
    if (encryptionKey.length < 32) {
      console.error('[OtpLogin] ✗ CRITICAL ERROR: otpEncryptionKey is too short!', {
        keyLength: encryptionKey.length,
        requiredLength: 32
      });
      if (onError) {
        onError('OTP encryption key must be at least 32 characters long.');
      }
      return;
    }
    
    console.log('[OtpLogin] ✓ Encryption key provided, length:', encryptionKey.length, otpEncryptionKey ? '(from prop)' : '(from VITE_SERVICE_ENCRYPTION_KEY)');
    
    try {
      core = new OtpLoginCore({
        apiUrl,
        onSuccess,
        onError,
        endpoints,
        customHeaders,
        otpEncryptionKey: encryptionKey, // CRITICAL: Pass encryption key for encrypting OTP requests
      });

      // Subscribe to state changes
      unsubscribe = core.subscribe((newState) => {
        state = newState;
      });
      
      console.log('[OtpLogin] Initialization complete');
    } catch (error) {
      console.error('[OtpLogin] Failed to initialize:', error);
      onError?.(error instanceof Error ? error.message : 'Failed to initialize login');
    }
  });

  onDestroy(() => {
    if (unsubscribe) {
      unsubscribe();
    }
    if (core) {
      core.destroy();
    }
  });

  function handleEmailChange(e: Event) {
    if (!core) return;
    const target = e.target as HTMLInputElement;
    core.setEmail(target.value);
  }

  function handleOtpChange(e: Event) {
    if (!core) return;
    const target = e.target as HTMLInputElement;
    core.setOtp(target.value);
  }

  function handleRequestOtp() {
    if (!core) return;
    core.requestOtp();
  }

  function handleVerifyOtp() {
    if (!core) return;
    core.verifyOtp();
  }

  function handleGoBack() {
    if (!core) return;
    core.goBack();
  }

  function handleClose(e: Event) {
    e.stopPropagation();
    if (onClose) {
      onClose();
    }
  }

  function handleKeyPress(e: KeyboardEvent, handler: () => void) {
    if (e.key === 'Enter' && !state.loading) {
      handler();
    }
  }

  // Computed values to avoid deeply nested conditionals in template
  $: showEmailForm = state.step === 'email';
  $: showOtpForm = state.step === 'otp';
  
  // Computed component to render - ensures we always have content for Svelte 5 runes mode
  // Default to 'email' if step is invalid to prevent empty blocks
  $: currentForm = showEmailForm ? 'email' : (showOtpForm ? 'otp' : 'email');
</script>

{#if showAsModal}
  <!-- Modal rendered inline with fixed positioning to escape parent containers -->
  <div 
    class="otp-login-modal-overlay" 
    onclick={() => onClose?.()} 
    role="button" 
    tabindex="0" 
    onkeydown={(e) => e.key === 'Escape' && onClose?.()}
  >
    <div class="otp-login-modal" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()} role="dialog" aria-labelledby="otp-login-title" tabindex="-1">
      <div class="otp-login-header">
        <h2 id="otp-login-title">{title}</h2>
        <button 
          type="button"
          class="otp-login-close" 
          class:hidden={!onClose}
          onclick={handleClose} 
          aria-label="Close"
          aria-hidden={!onClose}
        >X</button>
      </div>
      <div class="otp-login-content">
        <ErrorDisplay {state} />
        {#if currentForm === 'email'}
          <EmailForm 
            {state}
            onEmailChange={handleEmailChange}
            onRequestOtp={handleRequestOtp}
            onKeyPress={handleKeyPress}
          />
        {:else}
          <OtpForm 
            {state}
            onOtpChange={handleOtpChange}
            onVerifyOtp={handleVerifyOtp}
            onGoBack={handleGoBack}
            onKeyPress={handleKeyPress}
          />
        {/if}
      </div>
    </div>
  </div>
{:else}
  <div class="otp-login">
    <div class="otp-login-container">
      <div class="otp-login-header">
        <h1 class="otp-login-title">{title}</h1>
        <p class="otp-login-subtitle">{subtitle}</p>
      </div>
      <ErrorDisplay {state} />
      {#if currentForm === 'email'}
        <EmailForm 
          {state}
          onEmailChange={handleEmailChange}
          onRequestOtp={handleRequestOtp}
          onKeyPress={handleKeyPress}
        />
      {:else}
        <OtpForm 
          {state}
          onOtpChange={handleOtpChange}
          onVerifyOtp={handleVerifyOtp}
          onGoBack={handleGoBack}
          onKeyPress={handleKeyPress}
        />
      {/if}
    </div>
  </div>
{/if}

<style lang="scss">
  @use '../../../shared-styles/animations' as *;
  @use '../../../shared-styles/mixins' as *;

  /* Standalone Login Form */
  .otp-login {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    padding: var(--spacing-xl);
    position: relative;
    z-index: 1;
    pointer-events: auto;
  }

  .otp-login-container {
    max-width: 400px;
    width: 100%;
    position: relative;
    z-index: 1;
    pointer-events: auto;
  }

  .otp-login-header {
    text-align: center;
    margin-bottom: var(--spacing-2xl);
  }

  .otp-login-title {
    font-size: 2rem;
    margin-bottom: var(--spacing-md);
    color: var(--accent);
  }

  .otp-login-subtitle {
    color: var(--text-secondary);
  }

  /* Modal Variant */
  .otp-login-modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000000; /* Must be higher than auth screen (999999) */
    animation: fade-in 0.3s ease-out;
    pointer-events: auto;
  }

  .otp-login-modal {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 12px;
    width: 90%;
    max-width: min(90vw, 500px);
    max-height: 90vh;
    overflow-y: auto;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
    @include gpu-accelerated;
  }

  .otp-login-modal .otp-login-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 24px;
    border-bottom: 1px solid var(--border);
    margin-bottom: 0;
    text-align: left;
  }

  .otp-login-modal h2 {
    margin: 0;
    font-size: 24px;
    color: var(--text);
  }

  .otp-login-close {
    background: none;
    border: none;
    font-size: 32px;
    color: var(--text-secondary);
    cursor: pointer;
    padding: 0;
    width: 32px;
    height: 32px;
    min-width: 32px;
    min-height: 32px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 4px;
    transition: all 0.2s;
    position: relative;
    z-index: 10;
    pointer-events: auto;
    
    &.hidden {
      display: none;
    }
    
    &:hover:not(.hidden) {
      background: var(--bg-secondary);
      color: var(--text);
    }
    
    &:active:not(.hidden) {
      transform: scale(0.95);
    }
  }

  .otp-login-modal .otp-login-content {
    padding: 24px;
  }

  .hidden {
    display: none;
  }
</style>
